cmake_minimum_required(VERSION 3.25)
project(test)

set(CMAKE_CXX_STANDARD 17)

include_directories(.)
include_directories(../)

find_package(GTest)

add_executable(cgo_coroutine_test cgo_coroutine_test.cpp)
add_executable(cgo_wait_test cgo_wait_test.cpp)
add_executable(cgo_performance1_test cgo_performance1_test.cpp)
add_executable(cgo_performance2_test cgo_performance2_test.cpp)
add_executable(cgo_chan_test cgo_chan_test.cpp)
add_executable(cgo_mutex_test cgo_mutex_test.cpp)
add_executable(cgo_performance3_test cgo_performance3_test.cpp)

if (CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
    target_link_libraries(cgo_coroutine_test cgo gtest::gtest)
    target_link_libraries(cgo_wait_test cgo gtest::gtest)
    target_link_libraries(cgo_performance1_test cgo gtest::gtest)
    target_link_libraries(cgo_performance2_test cgo gtest::gtest)
    target_link_libraries(cgo_performance3_test cgo gtest::gtest)
    target_link_libraries(cgo_chan_test cgo gtest::gtest)
    target_link_libraries(cgo_mutex_test cgo gtest::gtest)
else ()
    target_link_libraries(cgo_coroutine_test dl pthread cgo gtest::gtest)
    target_link_libraries(cgo_wait_test dl pthread cgo gtest::gtest)
    target_link_libraries(cgo_performance1_test dl pthread cgo gtest::gtest)
    target_link_libraries(cgo_performance2_test dl pthread cgo gtest::gtest)
    target_link_libraries(cgo_performance3_test dl pthread cgo gtest::gtest)
    target_link_libraries(cgo_chan_test dl pthread cgo gtest::gtest)
    target_link_libraries(cgo_mutex_test dl pthread cgo gtest::gtest)
endif ()