cmake_minimum_required(VERSION 3.25)
project(cgo_project)

if (ONLY_CGO)
    add_subdirectory(cgo)
else ()
    add_subdirectory(cgo)
    add_subdirectory(tutorial/curl-example)
    add_subdirectory(tutorial/redis-example)
    add_subdirectory(tutorial/mysql-example)
    add_subdirectory(tutorial/net-examples/tcp-server-example)
    add_subdirectory(tutorial/net-examples/tcp-client-example)
    add_subdirectory(tutorial/net-examples/udp-server-example)
    add_subdirectory(tutorial/net-examples/udp-client-example)
    add_subdirectory(tutorial/grpc-example/grpc-server-example)
    add_subdirectory(tutorial/grpc-example/grpc-client-example)
endif ()