syntax = "proto3";
package protocol;
import "request_response.proto";

option go_package="./protocol;protocol";

service TestService {
  rpc GetUser(GetUserReq) returns (GetUserRsp) {}

  rpc CStream(stream GetUserReq) returns (GetUserRsp) {}

  rpc SStream(GetUserReq) returns (stream GetUserRsp) {}

  rpc BStream(stream GetUserReq) returns (stream GetUserRsp) {}

  rpc GetUser2(GetUserReq) returns (GetUserRsp) {}
}

service HallService {
  rpc GetUser(GetUserReq) returns (GetUserRsp) {}

  rpc CStream(stream GetUserReq) returns (GetUserRsp) {}

  rpc SStream(GetUserReq) returns (stream GetUserRsp) {}

  rpc BStream(stream GetUserReq) returns (stream GetUserRsp) {}

  rpc GetUser2(GetUserReq) returns (GetUserRsp) {}
}