// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: config.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_config_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_config_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_config_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_config_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_config_2eproto;
namespace rmdb {
class RmdbConfig;
struct RmdbConfigDefaultTypeInternal;
extern RmdbConfigDefaultTypeInternal _RmdbConfig_default_instance_;
class RmdbUnit;
struct RmdbUnitDefaultTypeInternal;
extern RmdbUnitDefaultTypeInternal _RmdbUnit_default_instance_;
}  // namespace rmdb
PROTOBUF_NAMESPACE_OPEN
template<> ::rmdb::RmdbConfig* Arena::CreateMaybeMessage<::rmdb::RmdbConfig>(Arena*);
template<> ::rmdb::RmdbUnit* Arena::CreateMaybeMessage<::rmdb::RmdbUnit>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace rmdb {

// ===================================================================

class RmdbUnit final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:rmdb.RmdbUnit) */ {
 public:
  inline RmdbUnit() : RmdbUnit(nullptr) {}
  ~RmdbUnit() override;
  explicit PROTOBUF_CONSTEXPR RmdbUnit(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RmdbUnit(const RmdbUnit& from);
  RmdbUnit(RmdbUnit&& from) noexcept
    : RmdbUnit() {
    *this = ::std::move(from);
  }

  inline RmdbUnit& operator=(const RmdbUnit& from) {
    CopyFrom(from);
    return *this;
  }
  inline RmdbUnit& operator=(RmdbUnit&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RmdbUnit& default_instance() {
    return *internal_default_instance();
  }
  static inline const RmdbUnit* internal_default_instance() {
    return reinterpret_cast<const RmdbUnit*>(
               &_RmdbUnit_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(RmdbUnit& a, RmdbUnit& b) {
    a.Swap(&b);
  }
  inline void Swap(RmdbUnit* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RmdbUnit* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RmdbUnit* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RmdbUnit>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RmdbUnit& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RmdbUnit& from) {
    RmdbUnit::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RmdbUnit* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "rmdb.RmdbUnit";
  }
  protected:
  explicit RmdbUnit(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAddrFieldNumber = 2,
    kIdFieldNumber = 1,
  };
  // string addr = 2;
  void clear_addr();
  const std::string& addr() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_addr(ArgT0&& arg0, ArgT... args);
  std::string* mutable_addr();
  PROTOBUF_NODISCARD std::string* release_addr();
  void set_allocated_addr(std::string* addr);
  private:
  const std::string& _internal_addr() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_addr(const std::string& value);
  std::string* _internal_mutable_addr();
  public:

  // uint32 id = 1;
  void clear_id();
  uint32_t id() const;
  void set_id(uint32_t value);
  private:
  uint32_t _internal_id() const;
  void _internal_set_id(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:rmdb.RmdbUnit)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr addr_;
    uint32_t id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_config_2eproto;
};
// -------------------------------------------------------------------

class RmdbConfig final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:rmdb.RmdbConfig) */ {
 public:
  inline RmdbConfig() : RmdbConfig(nullptr) {}
  ~RmdbConfig() override;
  explicit PROTOBUF_CONSTEXPR RmdbConfig(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RmdbConfig(const RmdbConfig& from);
  RmdbConfig(RmdbConfig&& from) noexcept
    : RmdbConfig() {
    *this = ::std::move(from);
  }

  inline RmdbConfig& operator=(const RmdbConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline RmdbConfig& operator=(RmdbConfig&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RmdbConfig& default_instance() {
    return *internal_default_instance();
  }
  static inline const RmdbConfig* internal_default_instance() {
    return reinterpret_cast<const RmdbConfig*>(
               &_RmdbConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(RmdbConfig& a, RmdbConfig& b) {
    a.Swap(&b);
  }
  inline void Swap(RmdbConfig* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RmdbConfig* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RmdbConfig* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RmdbConfig>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RmdbConfig& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RmdbConfig& from) {
    RmdbConfig::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RmdbConfig* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "rmdb.RmdbConfig";
  }
  protected:
  explicit RmdbConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUnitsFieldNumber = 1,
  };
  // repeated .rmdb.RmdbUnit units = 1;
  int units_size() const;
  private:
  int _internal_units_size() const;
  public:
  void clear_units();
  ::rmdb::RmdbUnit* mutable_units(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::rmdb::RmdbUnit >*
      mutable_units();
  private:
  const ::rmdb::RmdbUnit& _internal_units(int index) const;
  ::rmdb::RmdbUnit* _internal_add_units();
  public:
  const ::rmdb::RmdbUnit& units(int index) const;
  ::rmdb::RmdbUnit* add_units();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::rmdb::RmdbUnit >&
      units() const;

  // @@protoc_insertion_point(class_scope:rmdb.RmdbConfig)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::rmdb::RmdbUnit > units_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_config_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// RmdbUnit

// uint32 id = 1;
inline void RmdbUnit::clear_id() {
  _impl_.id_ = 0u;
}
inline uint32_t RmdbUnit::_internal_id() const {
  return _impl_.id_;
}
inline uint32_t RmdbUnit::id() const {
  // @@protoc_insertion_point(field_get:rmdb.RmdbUnit.id)
  return _internal_id();
}
inline void RmdbUnit::_internal_set_id(uint32_t value) {
  
  _impl_.id_ = value;
}
inline void RmdbUnit::set_id(uint32_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:rmdb.RmdbUnit.id)
}

// string addr = 2;
inline void RmdbUnit::clear_addr() {
  _impl_.addr_.ClearToEmpty();
}
inline const std::string& RmdbUnit::addr() const {
  // @@protoc_insertion_point(field_get:rmdb.RmdbUnit.addr)
  return _internal_addr();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RmdbUnit::set_addr(ArgT0&& arg0, ArgT... args) {
 
 _impl_.addr_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:rmdb.RmdbUnit.addr)
}
inline std::string* RmdbUnit::mutable_addr() {
  std::string* _s = _internal_mutable_addr();
  // @@protoc_insertion_point(field_mutable:rmdb.RmdbUnit.addr)
  return _s;
}
inline const std::string& RmdbUnit::_internal_addr() const {
  return _impl_.addr_.Get();
}
inline void RmdbUnit::_internal_set_addr(const std::string& value) {
  
  _impl_.addr_.Set(value, GetArenaForAllocation());
}
inline std::string* RmdbUnit::_internal_mutable_addr() {
  
  return _impl_.addr_.Mutable(GetArenaForAllocation());
}
inline std::string* RmdbUnit::release_addr() {
  // @@protoc_insertion_point(field_release:rmdb.RmdbUnit.addr)
  return _impl_.addr_.Release();
}
inline void RmdbUnit::set_allocated_addr(std::string* addr) {
  if (addr != nullptr) {
    
  } else {
    
  }
  _impl_.addr_.SetAllocated(addr, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.addr_.IsDefault()) {
    _impl_.addr_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:rmdb.RmdbUnit.addr)
}

// -------------------------------------------------------------------

// RmdbConfig

// repeated .rmdb.RmdbUnit units = 1;
inline int RmdbConfig::_internal_units_size() const {
  return _impl_.units_.size();
}
inline int RmdbConfig::units_size() const {
  return _internal_units_size();
}
inline void RmdbConfig::clear_units() {
  _impl_.units_.Clear();
}
inline ::rmdb::RmdbUnit* RmdbConfig::mutable_units(int index) {
  // @@protoc_insertion_point(field_mutable:rmdb.RmdbConfig.units)
  return _impl_.units_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::rmdb::RmdbUnit >*
RmdbConfig::mutable_units() {
  // @@protoc_insertion_point(field_mutable_list:rmdb.RmdbConfig.units)
  return &_impl_.units_;
}
inline const ::rmdb::RmdbUnit& RmdbConfig::_internal_units(int index) const {
  return _impl_.units_.Get(index);
}
inline const ::rmdb::RmdbUnit& RmdbConfig::units(int index) const {
  // @@protoc_insertion_point(field_get:rmdb.RmdbConfig.units)
  return _internal_units(index);
}
inline ::rmdb::RmdbUnit* RmdbConfig::_internal_add_units() {
  return _impl_.units_.Add();
}
inline ::rmdb::RmdbUnit* RmdbConfig::add_units() {
  ::rmdb::RmdbUnit* _add = _internal_add_units();
  // @@protoc_insertion_point(field_add:rmdb.RmdbConfig.units)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::rmdb::RmdbUnit >&
RmdbConfig::units() const {
  // @@protoc_insertion_point(field_list:rmdb.RmdbConfig.units)
  return _impl_.units_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace rmdb

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_config_2eproto
