// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meta.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_meta_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_meta_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_meta_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_meta_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_meta_2eproto;
namespace rmdb {
class KeyData;
struct KeyDataDefaultTypeInternal;
extern KeyDataDefaultTypeInternal _KeyData_default_instance_;
class MetaData;
struct MetaDataDefaultTypeInternal;
extern MetaDataDefaultTypeInternal _MetaData_default_instance_;
class MetaData_KeysEntry_DoNotUse;
struct MetaData_KeysEntry_DoNotUseDefaultTypeInternal;
extern MetaData_KeysEntry_DoNotUseDefaultTypeInternal _MetaData_KeysEntry_DoNotUse_default_instance_;
}  // namespace rmdb
PROTOBUF_NAMESPACE_OPEN
template<> ::rmdb::KeyData* Arena::CreateMaybeMessage<::rmdb::KeyData>(Arena*);
template<> ::rmdb::MetaData* Arena::CreateMaybeMessage<::rmdb::MetaData>(Arena*);
template<> ::rmdb::MetaData_KeysEntry_DoNotUse* Arena::CreateMaybeMessage<::rmdb::MetaData_KeysEntry_DoNotUse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace rmdb {

enum ContentType : int {
  PLAIN = 0,
  binary = 1,
  BSON = 2,
  ContentType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ContentType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ContentType_IsValid(int value);
constexpr ContentType ContentType_MIN = PLAIN;
constexpr ContentType ContentType_MAX = BSON;
constexpr int ContentType_ARRAYSIZE = ContentType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ContentType_descriptor();
template<typename T>
inline const std::string& ContentType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ContentType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ContentType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ContentType_descriptor(), enum_t_value);
}
inline bool ContentType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ContentType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ContentType>(
    ContentType_descriptor(), name, value);
}
// ===================================================================

class KeyData final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:rmdb.KeyData) */ {
 public:
  inline KeyData() : KeyData(nullptr) {}
  ~KeyData() override;
  explicit PROTOBUF_CONSTEXPR KeyData(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  KeyData(const KeyData& from);
  KeyData(KeyData&& from) noexcept
    : KeyData() {
    *this = ::std::move(from);
  }

  inline KeyData& operator=(const KeyData& from) {
    CopyFrom(from);
    return *this;
  }
  inline KeyData& operator=(KeyData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const KeyData& default_instance() {
    return *internal_default_instance();
  }
  static inline const KeyData* internal_default_instance() {
    return reinterpret_cast<const KeyData*>(
               &_KeyData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(KeyData& a, KeyData& b) {
    a.Swap(&b);
  }
  inline void Swap(KeyData* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(KeyData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  KeyData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<KeyData>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const KeyData& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const KeyData& from) {
    KeyData::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(KeyData* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "rmdb.KeyData";
  }
  protected:
  explicit KeyData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kKeyFieldNumber = 1,
    kValFieldNumber = 2,
  };
  // string key = 1;
  void clear_key();
  const std::string& key() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_key(ArgT0&& arg0, ArgT... args);
  std::string* mutable_key();
  PROTOBUF_NODISCARD std::string* release_key();
  void set_allocated_key(std::string* key);
  private:
  const std::string& _internal_key() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_key(const std::string& value);
  std::string* _internal_mutable_key();
  public:

  // string val = 2;
  void clear_val();
  const std::string& val() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_val(ArgT0&& arg0, ArgT... args);
  std::string* mutable_val();
  PROTOBUF_NODISCARD std::string* release_val();
  void set_allocated_val(std::string* val);
  private:
  const std::string& _internal_val() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_val(const std::string& value);
  std::string* _internal_mutable_val();
  public:

  // @@protoc_insertion_point(class_scope:rmdb.KeyData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr key_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr val_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_meta_2eproto;
};
// -------------------------------------------------------------------

class MetaData_KeysEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<MetaData_KeysEntry_DoNotUse, 
    std::string, std::string,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<MetaData_KeysEntry_DoNotUse, 
    std::string, std::string,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING> SuperType;
  MetaData_KeysEntry_DoNotUse();
  explicit PROTOBUF_CONSTEXPR MetaData_KeysEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit MetaData_KeysEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const MetaData_KeysEntry_DoNotUse& other);
  static const MetaData_KeysEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const MetaData_KeysEntry_DoNotUse*>(&_MetaData_KeysEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "rmdb.MetaData.KeysEntry.key");
 }
  static bool ValidateValue(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "rmdb.MetaData.KeysEntry.value");
 }
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  friend struct ::TableStruct_meta_2eproto;
};

// -------------------------------------------------------------------

class MetaData final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:rmdb.MetaData) */ {
 public:
  inline MetaData() : MetaData(nullptr) {}
  ~MetaData() override;
  explicit PROTOBUF_CONSTEXPR MetaData(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MetaData(const MetaData& from);
  MetaData(MetaData&& from) noexcept
    : MetaData() {
    *this = ::std::move(from);
  }

  inline MetaData& operator=(const MetaData& from) {
    CopyFrom(from);
    return *this;
  }
  inline MetaData& operator=(MetaData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MetaData& default_instance() {
    return *internal_default_instance();
  }
  static inline const MetaData* internal_default_instance() {
    return reinterpret_cast<const MetaData*>(
               &_MetaData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(MetaData& a, MetaData& b) {
    a.Swap(&b);
  }
  inline void Swap(MetaData* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MetaData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MetaData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MetaData>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const MetaData& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const MetaData& from) {
    MetaData::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MetaData* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "rmdb.MetaData";
  }
  protected:
  explicit MetaData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kKeysFieldNumber = 2,
    kTableFieldNumber = 1,
    kDbFieldNumber = 5,
    kCacheExpireFieldNumber = 3,
    kTypeFieldNumber = 4,
  };
  // map<string, string> keys = 2;
  int keys_size() const;
  private:
  int _internal_keys_size() const;
  public:
  void clear_keys();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
      _internal_keys() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
      _internal_mutable_keys();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
      keys() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
      mutable_keys();

  // string table = 1;
  void clear_table();
  const std::string& table() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_table(ArgT0&& arg0, ArgT... args);
  std::string* mutable_table();
  PROTOBUF_NODISCARD std::string* release_table();
  void set_allocated_table(std::string* table);
  private:
  const std::string& _internal_table() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_table(const std::string& value);
  std::string* _internal_mutable_table();
  public:

  // string db = 5;
  void clear_db();
  const std::string& db() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_db(ArgT0&& arg0, ArgT... args);
  std::string* mutable_db();
  PROTOBUF_NODISCARD std::string* release_db();
  void set_allocated_db(std::string* db);
  private:
  const std::string& _internal_db() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_db(const std::string& value);
  std::string* _internal_mutable_db();
  public:

  // uint32 cache_expire = 3;
  void clear_cache_expire();
  uint32_t cache_expire() const;
  void set_cache_expire(uint32_t value);
  private:
  uint32_t _internal_cache_expire() const;
  void _internal_set_cache_expire(uint32_t value);
  public:

  // .rmdb.ContentType type = 4;
  void clear_type();
  ::rmdb::ContentType type() const;
  void set_type(::rmdb::ContentType value);
  private:
  ::rmdb::ContentType _internal_type() const;
  void _internal_set_type(::rmdb::ContentType value);
  public:

  // @@protoc_insertion_point(class_scope:rmdb.MetaData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::MapField<
        MetaData_KeysEntry_DoNotUse,
        std::string, std::string,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING> keys_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr table_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr db_;
    uint32_t cache_expire_;
    int type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_meta_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// KeyData

// string key = 1;
inline void KeyData::clear_key() {
  _impl_.key_.ClearToEmpty();
}
inline const std::string& KeyData::key() const {
  // @@protoc_insertion_point(field_get:rmdb.KeyData.key)
  return _internal_key();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void KeyData::set_key(ArgT0&& arg0, ArgT... args) {
 
 _impl_.key_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:rmdb.KeyData.key)
}
inline std::string* KeyData::mutable_key() {
  std::string* _s = _internal_mutable_key();
  // @@protoc_insertion_point(field_mutable:rmdb.KeyData.key)
  return _s;
}
inline const std::string& KeyData::_internal_key() const {
  return _impl_.key_.Get();
}
inline void KeyData::_internal_set_key(const std::string& value) {
  
  _impl_.key_.Set(value, GetArenaForAllocation());
}
inline std::string* KeyData::_internal_mutable_key() {
  
  return _impl_.key_.Mutable(GetArenaForAllocation());
}
inline std::string* KeyData::release_key() {
  // @@protoc_insertion_point(field_release:rmdb.KeyData.key)
  return _impl_.key_.Release();
}
inline void KeyData::set_allocated_key(std::string* key) {
  if (key != nullptr) {
    
  } else {
    
  }
  _impl_.key_.SetAllocated(key, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.key_.IsDefault()) {
    _impl_.key_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:rmdb.KeyData.key)
}

// string val = 2;
inline void KeyData::clear_val() {
  _impl_.val_.ClearToEmpty();
}
inline const std::string& KeyData::val() const {
  // @@protoc_insertion_point(field_get:rmdb.KeyData.val)
  return _internal_val();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void KeyData::set_val(ArgT0&& arg0, ArgT... args) {
 
 _impl_.val_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:rmdb.KeyData.val)
}
inline std::string* KeyData::mutable_val() {
  std::string* _s = _internal_mutable_val();
  // @@protoc_insertion_point(field_mutable:rmdb.KeyData.val)
  return _s;
}
inline const std::string& KeyData::_internal_val() const {
  return _impl_.val_.Get();
}
inline void KeyData::_internal_set_val(const std::string& value) {
  
  _impl_.val_.Set(value, GetArenaForAllocation());
}
inline std::string* KeyData::_internal_mutable_val() {
  
  return _impl_.val_.Mutable(GetArenaForAllocation());
}
inline std::string* KeyData::release_val() {
  // @@protoc_insertion_point(field_release:rmdb.KeyData.val)
  return _impl_.val_.Release();
}
inline void KeyData::set_allocated_val(std::string* val) {
  if (val != nullptr) {
    
  } else {
    
  }
  _impl_.val_.SetAllocated(val, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.val_.IsDefault()) {
    _impl_.val_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:rmdb.KeyData.val)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// MetaData

// string table = 1;
inline void MetaData::clear_table() {
  _impl_.table_.ClearToEmpty();
}
inline const std::string& MetaData::table() const {
  // @@protoc_insertion_point(field_get:rmdb.MetaData.table)
  return _internal_table();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void MetaData::set_table(ArgT0&& arg0, ArgT... args) {
 
 _impl_.table_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:rmdb.MetaData.table)
}
inline std::string* MetaData::mutable_table() {
  std::string* _s = _internal_mutable_table();
  // @@protoc_insertion_point(field_mutable:rmdb.MetaData.table)
  return _s;
}
inline const std::string& MetaData::_internal_table() const {
  return _impl_.table_.Get();
}
inline void MetaData::_internal_set_table(const std::string& value) {
  
  _impl_.table_.Set(value, GetArenaForAllocation());
}
inline std::string* MetaData::_internal_mutable_table() {
  
  return _impl_.table_.Mutable(GetArenaForAllocation());
}
inline std::string* MetaData::release_table() {
  // @@protoc_insertion_point(field_release:rmdb.MetaData.table)
  return _impl_.table_.Release();
}
inline void MetaData::set_allocated_table(std::string* table) {
  if (table != nullptr) {
    
  } else {
    
  }
  _impl_.table_.SetAllocated(table, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.table_.IsDefault()) {
    _impl_.table_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:rmdb.MetaData.table)
}

// map<string, string> keys = 2;
inline int MetaData::_internal_keys_size() const {
  return _impl_.keys_.size();
}
inline int MetaData::keys_size() const {
  return _internal_keys_size();
}
inline void MetaData::clear_keys() {
  _impl_.keys_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
MetaData::_internal_keys() const {
  return _impl_.keys_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
MetaData::keys() const {
  // @@protoc_insertion_point(field_map:rmdb.MetaData.keys)
  return _internal_keys();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
MetaData::_internal_mutable_keys() {
  return _impl_.keys_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
MetaData::mutable_keys() {
  // @@protoc_insertion_point(field_mutable_map:rmdb.MetaData.keys)
  return _internal_mutable_keys();
}

// uint32 cache_expire = 3;
inline void MetaData::clear_cache_expire() {
  _impl_.cache_expire_ = 0u;
}
inline uint32_t MetaData::_internal_cache_expire() const {
  return _impl_.cache_expire_;
}
inline uint32_t MetaData::cache_expire() const {
  // @@protoc_insertion_point(field_get:rmdb.MetaData.cache_expire)
  return _internal_cache_expire();
}
inline void MetaData::_internal_set_cache_expire(uint32_t value) {
  
  _impl_.cache_expire_ = value;
}
inline void MetaData::set_cache_expire(uint32_t value) {
  _internal_set_cache_expire(value);
  // @@protoc_insertion_point(field_set:rmdb.MetaData.cache_expire)
}

// .rmdb.ContentType type = 4;
inline void MetaData::clear_type() {
  _impl_.type_ = 0;
}
inline ::rmdb::ContentType MetaData::_internal_type() const {
  return static_cast< ::rmdb::ContentType >(_impl_.type_);
}
inline ::rmdb::ContentType MetaData::type() const {
  // @@protoc_insertion_point(field_get:rmdb.MetaData.type)
  return _internal_type();
}
inline void MetaData::_internal_set_type(::rmdb::ContentType value) {
  
  _impl_.type_ = value;
}
inline void MetaData::set_type(::rmdb::ContentType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:rmdb.MetaData.type)
}

// string db = 5;
inline void MetaData::clear_db() {
  _impl_.db_.ClearToEmpty();
}
inline const std::string& MetaData::db() const {
  // @@protoc_insertion_point(field_get:rmdb.MetaData.db)
  return _internal_db();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void MetaData::set_db(ArgT0&& arg0, ArgT... args) {
 
 _impl_.db_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:rmdb.MetaData.db)
}
inline std::string* MetaData::mutable_db() {
  std::string* _s = _internal_mutable_db();
  // @@protoc_insertion_point(field_mutable:rmdb.MetaData.db)
  return _s;
}
inline const std::string& MetaData::_internal_db() const {
  return _impl_.db_.Get();
}
inline void MetaData::_internal_set_db(const std::string& value) {
  
  _impl_.db_.Set(value, GetArenaForAllocation());
}
inline std::string* MetaData::_internal_mutable_db() {
  
  return _impl_.db_.Mutable(GetArenaForAllocation());
}
inline std::string* MetaData::release_db() {
  // @@protoc_insertion_point(field_release:rmdb.MetaData.db)
  return _impl_.db_.Release();
}
inline void MetaData::set_allocated_db(std::string* db) {
  if (db != nullptr) {
    
  } else {
    
  }
  _impl_.db_.SetAllocated(db, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.db_.IsDefault()) {
    _impl_.db_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:rmdb.MetaData.db)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace rmdb

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::rmdb::ContentType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::rmdb::ContentType>() {
  return ::rmdb::ContentType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_meta_2eproto
