// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: rmdb.proto

#include "rmdb.pb.h"
#include "rmdb.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace rmdb {

static const char* RmDb_method_names[] = {
  "/rmdb.RmDb/Set",
  "/rmdb.RmDb/SetNx",
  "/rmdb.RmDb/Get",
  "/rmdb.RmDb/Del",
  "/rmdb.RmDb/Update",
  "/rmdb.RmDb/BatchSet",
  "/rmdb.RmDb/BatchSetNx",
  "/rmdb.RmDb/BatchGet",
  "/rmdb.RmDb/BatchDel",
  "/rmdb.RmDb/BatchUpdate",
  "/rmdb.RmDb/GetCount",
  "/rmdb.RmDb/GetMeta",
  "/rmdb.RmDb/ClusterInfo",
  "/rmdb.RmDb/Match",
  "/rmdb.RmDb/Find",
  "/rmdb.RmDb/UpdateKey",
};

std::unique_ptr< RmDb::Stub> RmDb::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< RmDb::Stub> stub(new RmDb::Stub(channel, options));
  return stub;
}

RmDb::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Set_(RmDb_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetNx_(RmDb_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Get_(RmDb_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Del_(RmDb_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Update_(RmDb_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_BatchSet_(RmDb_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_BatchSetNx_(RmDb_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_BatchGet_(RmDb_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_BatchDel_(RmDb_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_BatchUpdate_(RmDb_method_names[9], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetCount_(RmDb_method_names[10], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetMeta_(RmDb_method_names[11], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ClusterInfo_(RmDb_method_names[12], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Match_(RmDb_method_names[13], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Find_(RmDb_method_names[14], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UpdateKey_(RmDb_method_names[15], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status RmDb::Stub::Set(::grpc::ClientContext* context, const ::rmdb::SetDataReq& request, ::rmdb::SetDataRsp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::rmdb::SetDataReq, ::rmdb::SetDataRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Set_, context, request, response);
}

void RmDb::Stub::async::Set(::grpc::ClientContext* context, const ::rmdb::SetDataReq* request, ::rmdb::SetDataRsp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::rmdb::SetDataReq, ::rmdb::SetDataRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Set_, context, request, response, std::move(f));
}

void RmDb::Stub::async::Set(::grpc::ClientContext* context, const ::rmdb::SetDataReq* request, ::rmdb::SetDataRsp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Set_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::rmdb::SetDataRsp>* RmDb::Stub::PrepareAsyncSetRaw(::grpc::ClientContext* context, const ::rmdb::SetDataReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::rmdb::SetDataRsp, ::rmdb::SetDataReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Set_, context, request);
}

::grpc::ClientAsyncResponseReader< ::rmdb::SetDataRsp>* RmDb::Stub::AsyncSetRaw(::grpc::ClientContext* context, const ::rmdb::SetDataReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status RmDb::Stub::SetNx(::grpc::ClientContext* context, const ::rmdb::SetNxDataReq& request, ::rmdb::SetNxDataRsp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::rmdb::SetNxDataReq, ::rmdb::SetNxDataRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetNx_, context, request, response);
}

void RmDb::Stub::async::SetNx(::grpc::ClientContext* context, const ::rmdb::SetNxDataReq* request, ::rmdb::SetNxDataRsp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::rmdb::SetNxDataReq, ::rmdb::SetNxDataRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetNx_, context, request, response, std::move(f));
}

void RmDb::Stub::async::SetNx(::grpc::ClientContext* context, const ::rmdb::SetNxDataReq* request, ::rmdb::SetNxDataRsp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetNx_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::rmdb::SetNxDataRsp>* RmDb::Stub::PrepareAsyncSetNxRaw(::grpc::ClientContext* context, const ::rmdb::SetNxDataReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::rmdb::SetNxDataRsp, ::rmdb::SetNxDataReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetNx_, context, request);
}

::grpc::ClientAsyncResponseReader< ::rmdb::SetNxDataRsp>* RmDb::Stub::AsyncSetNxRaw(::grpc::ClientContext* context, const ::rmdb::SetNxDataReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetNxRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status RmDb::Stub::Get(::grpc::ClientContext* context, const ::rmdb::GetDataReq& request, ::rmdb::GetDataRsp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::rmdb::GetDataReq, ::rmdb::GetDataRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Get_, context, request, response);
}

void RmDb::Stub::async::Get(::grpc::ClientContext* context, const ::rmdb::GetDataReq* request, ::rmdb::GetDataRsp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::rmdb::GetDataReq, ::rmdb::GetDataRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Get_, context, request, response, std::move(f));
}

void RmDb::Stub::async::Get(::grpc::ClientContext* context, const ::rmdb::GetDataReq* request, ::rmdb::GetDataRsp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Get_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::rmdb::GetDataRsp>* RmDb::Stub::PrepareAsyncGetRaw(::grpc::ClientContext* context, const ::rmdb::GetDataReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::rmdb::GetDataRsp, ::rmdb::GetDataReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Get_, context, request);
}

::grpc::ClientAsyncResponseReader< ::rmdb::GetDataRsp>* RmDb::Stub::AsyncGetRaw(::grpc::ClientContext* context, const ::rmdb::GetDataReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status RmDb::Stub::Del(::grpc::ClientContext* context, const ::rmdb::DelDataReq& request, ::rmdb::DelDataRsp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::rmdb::DelDataReq, ::rmdb::DelDataRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Del_, context, request, response);
}

void RmDb::Stub::async::Del(::grpc::ClientContext* context, const ::rmdb::DelDataReq* request, ::rmdb::DelDataRsp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::rmdb::DelDataReq, ::rmdb::DelDataRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Del_, context, request, response, std::move(f));
}

void RmDb::Stub::async::Del(::grpc::ClientContext* context, const ::rmdb::DelDataReq* request, ::rmdb::DelDataRsp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Del_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::rmdb::DelDataRsp>* RmDb::Stub::PrepareAsyncDelRaw(::grpc::ClientContext* context, const ::rmdb::DelDataReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::rmdb::DelDataRsp, ::rmdb::DelDataReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Del_, context, request);
}

::grpc::ClientAsyncResponseReader< ::rmdb::DelDataRsp>* RmDb::Stub::AsyncDelRaw(::grpc::ClientContext* context, const ::rmdb::DelDataReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDelRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status RmDb::Stub::Update(::grpc::ClientContext* context, const ::rmdb::UpdateDataReq& request, ::rmdb::UpdateDataRsp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::rmdb::UpdateDataReq, ::rmdb::UpdateDataRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Update_, context, request, response);
}

void RmDb::Stub::async::Update(::grpc::ClientContext* context, const ::rmdb::UpdateDataReq* request, ::rmdb::UpdateDataRsp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::rmdb::UpdateDataReq, ::rmdb::UpdateDataRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Update_, context, request, response, std::move(f));
}

void RmDb::Stub::async::Update(::grpc::ClientContext* context, const ::rmdb::UpdateDataReq* request, ::rmdb::UpdateDataRsp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Update_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::rmdb::UpdateDataRsp>* RmDb::Stub::PrepareAsyncUpdateRaw(::grpc::ClientContext* context, const ::rmdb::UpdateDataReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::rmdb::UpdateDataRsp, ::rmdb::UpdateDataReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Update_, context, request);
}

::grpc::ClientAsyncResponseReader< ::rmdb::UpdateDataRsp>* RmDb::Stub::AsyncUpdateRaw(::grpc::ClientContext* context, const ::rmdb::UpdateDataReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncUpdateRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status RmDb::Stub::BatchSet(::grpc::ClientContext* context, const ::rmdb::BatchSetDataReq& request, ::rmdb::BatchSetDataRsp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::rmdb::BatchSetDataReq, ::rmdb::BatchSetDataRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_BatchSet_, context, request, response);
}

void RmDb::Stub::async::BatchSet(::grpc::ClientContext* context, const ::rmdb::BatchSetDataReq* request, ::rmdb::BatchSetDataRsp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::rmdb::BatchSetDataReq, ::rmdb::BatchSetDataRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_BatchSet_, context, request, response, std::move(f));
}

void RmDb::Stub::async::BatchSet(::grpc::ClientContext* context, const ::rmdb::BatchSetDataReq* request, ::rmdb::BatchSetDataRsp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_BatchSet_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::rmdb::BatchSetDataRsp>* RmDb::Stub::PrepareAsyncBatchSetRaw(::grpc::ClientContext* context, const ::rmdb::BatchSetDataReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::rmdb::BatchSetDataRsp, ::rmdb::BatchSetDataReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_BatchSet_, context, request);
}

::grpc::ClientAsyncResponseReader< ::rmdb::BatchSetDataRsp>* RmDb::Stub::AsyncBatchSetRaw(::grpc::ClientContext* context, const ::rmdb::BatchSetDataReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncBatchSetRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status RmDb::Stub::BatchSetNx(::grpc::ClientContext* context, const ::rmdb::BatchSetNxDataReq& request, ::rmdb::BatchSetNxDataRsp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::rmdb::BatchSetNxDataReq, ::rmdb::BatchSetNxDataRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_BatchSetNx_, context, request, response);
}

void RmDb::Stub::async::BatchSetNx(::grpc::ClientContext* context, const ::rmdb::BatchSetNxDataReq* request, ::rmdb::BatchSetNxDataRsp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::rmdb::BatchSetNxDataReq, ::rmdb::BatchSetNxDataRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_BatchSetNx_, context, request, response, std::move(f));
}

void RmDb::Stub::async::BatchSetNx(::grpc::ClientContext* context, const ::rmdb::BatchSetNxDataReq* request, ::rmdb::BatchSetNxDataRsp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_BatchSetNx_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::rmdb::BatchSetNxDataRsp>* RmDb::Stub::PrepareAsyncBatchSetNxRaw(::grpc::ClientContext* context, const ::rmdb::BatchSetNxDataReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::rmdb::BatchSetNxDataRsp, ::rmdb::BatchSetNxDataReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_BatchSetNx_, context, request);
}

::grpc::ClientAsyncResponseReader< ::rmdb::BatchSetNxDataRsp>* RmDb::Stub::AsyncBatchSetNxRaw(::grpc::ClientContext* context, const ::rmdb::BatchSetNxDataReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncBatchSetNxRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status RmDb::Stub::BatchGet(::grpc::ClientContext* context, const ::rmdb::BatchGetDataReq& request, ::rmdb::BatchGetDataRsp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::rmdb::BatchGetDataReq, ::rmdb::BatchGetDataRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_BatchGet_, context, request, response);
}

void RmDb::Stub::async::BatchGet(::grpc::ClientContext* context, const ::rmdb::BatchGetDataReq* request, ::rmdb::BatchGetDataRsp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::rmdb::BatchGetDataReq, ::rmdb::BatchGetDataRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_BatchGet_, context, request, response, std::move(f));
}

void RmDb::Stub::async::BatchGet(::grpc::ClientContext* context, const ::rmdb::BatchGetDataReq* request, ::rmdb::BatchGetDataRsp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_BatchGet_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::rmdb::BatchGetDataRsp>* RmDb::Stub::PrepareAsyncBatchGetRaw(::grpc::ClientContext* context, const ::rmdb::BatchGetDataReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::rmdb::BatchGetDataRsp, ::rmdb::BatchGetDataReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_BatchGet_, context, request);
}

::grpc::ClientAsyncResponseReader< ::rmdb::BatchGetDataRsp>* RmDb::Stub::AsyncBatchGetRaw(::grpc::ClientContext* context, const ::rmdb::BatchGetDataReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncBatchGetRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status RmDb::Stub::BatchDel(::grpc::ClientContext* context, const ::rmdb::BatchDelDataReq& request, ::rmdb::BatchDelDataRsp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::rmdb::BatchDelDataReq, ::rmdb::BatchDelDataRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_BatchDel_, context, request, response);
}

void RmDb::Stub::async::BatchDel(::grpc::ClientContext* context, const ::rmdb::BatchDelDataReq* request, ::rmdb::BatchDelDataRsp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::rmdb::BatchDelDataReq, ::rmdb::BatchDelDataRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_BatchDel_, context, request, response, std::move(f));
}

void RmDb::Stub::async::BatchDel(::grpc::ClientContext* context, const ::rmdb::BatchDelDataReq* request, ::rmdb::BatchDelDataRsp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_BatchDel_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::rmdb::BatchDelDataRsp>* RmDb::Stub::PrepareAsyncBatchDelRaw(::grpc::ClientContext* context, const ::rmdb::BatchDelDataReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::rmdb::BatchDelDataRsp, ::rmdb::BatchDelDataReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_BatchDel_, context, request);
}

::grpc::ClientAsyncResponseReader< ::rmdb::BatchDelDataRsp>* RmDb::Stub::AsyncBatchDelRaw(::grpc::ClientContext* context, const ::rmdb::BatchDelDataReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncBatchDelRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status RmDb::Stub::BatchUpdate(::grpc::ClientContext* context, const ::rmdb::BatchUpdateDataReq& request, ::rmdb::BatchUpdateDataRsp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::rmdb::BatchUpdateDataReq, ::rmdb::BatchUpdateDataRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_BatchUpdate_, context, request, response);
}

void RmDb::Stub::async::BatchUpdate(::grpc::ClientContext* context, const ::rmdb::BatchUpdateDataReq* request, ::rmdb::BatchUpdateDataRsp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::rmdb::BatchUpdateDataReq, ::rmdb::BatchUpdateDataRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_BatchUpdate_, context, request, response, std::move(f));
}

void RmDb::Stub::async::BatchUpdate(::grpc::ClientContext* context, const ::rmdb::BatchUpdateDataReq* request, ::rmdb::BatchUpdateDataRsp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_BatchUpdate_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::rmdb::BatchUpdateDataRsp>* RmDb::Stub::PrepareAsyncBatchUpdateRaw(::grpc::ClientContext* context, const ::rmdb::BatchUpdateDataReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::rmdb::BatchUpdateDataRsp, ::rmdb::BatchUpdateDataReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_BatchUpdate_, context, request);
}

::grpc::ClientAsyncResponseReader< ::rmdb::BatchUpdateDataRsp>* RmDb::Stub::AsyncBatchUpdateRaw(::grpc::ClientContext* context, const ::rmdb::BatchUpdateDataReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncBatchUpdateRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status RmDb::Stub::GetCount(::grpc::ClientContext* context, const ::rmdb::GetDataCountReq& request, ::rmdb::GetDataCountRsp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::rmdb::GetDataCountReq, ::rmdb::GetDataCountRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetCount_, context, request, response);
}

void RmDb::Stub::async::GetCount(::grpc::ClientContext* context, const ::rmdb::GetDataCountReq* request, ::rmdb::GetDataCountRsp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::rmdb::GetDataCountReq, ::rmdb::GetDataCountRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetCount_, context, request, response, std::move(f));
}

void RmDb::Stub::async::GetCount(::grpc::ClientContext* context, const ::rmdb::GetDataCountReq* request, ::rmdb::GetDataCountRsp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetCount_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::rmdb::GetDataCountRsp>* RmDb::Stub::PrepareAsyncGetCountRaw(::grpc::ClientContext* context, const ::rmdb::GetDataCountReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::rmdb::GetDataCountRsp, ::rmdb::GetDataCountReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetCount_, context, request);
}

::grpc::ClientAsyncResponseReader< ::rmdb::GetDataCountRsp>* RmDb::Stub::AsyncGetCountRaw(::grpc::ClientContext* context, const ::rmdb::GetDataCountReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetCountRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status RmDb::Stub::GetMeta(::grpc::ClientContext* context, const ::rmdb::GetMetaReq& request, ::rmdb::GetMetaRsp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::rmdb::GetMetaReq, ::rmdb::GetMetaRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetMeta_, context, request, response);
}

void RmDb::Stub::async::GetMeta(::grpc::ClientContext* context, const ::rmdb::GetMetaReq* request, ::rmdb::GetMetaRsp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::rmdb::GetMetaReq, ::rmdb::GetMetaRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetMeta_, context, request, response, std::move(f));
}

void RmDb::Stub::async::GetMeta(::grpc::ClientContext* context, const ::rmdb::GetMetaReq* request, ::rmdb::GetMetaRsp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetMeta_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::rmdb::GetMetaRsp>* RmDb::Stub::PrepareAsyncGetMetaRaw(::grpc::ClientContext* context, const ::rmdb::GetMetaReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::rmdb::GetMetaRsp, ::rmdb::GetMetaReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetMeta_, context, request);
}

::grpc::ClientAsyncResponseReader< ::rmdb::GetMetaRsp>* RmDb::Stub::AsyncGetMetaRaw(::grpc::ClientContext* context, const ::rmdb::GetMetaReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetMetaRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status RmDb::Stub::ClusterInfo(::grpc::ClientContext* context, const ::rmdb::ClusterInfoReq& request, ::rmdb::ClusterInfoRsp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::rmdb::ClusterInfoReq, ::rmdb::ClusterInfoRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ClusterInfo_, context, request, response);
}

void RmDb::Stub::async::ClusterInfo(::grpc::ClientContext* context, const ::rmdb::ClusterInfoReq* request, ::rmdb::ClusterInfoRsp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::rmdb::ClusterInfoReq, ::rmdb::ClusterInfoRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ClusterInfo_, context, request, response, std::move(f));
}

void RmDb::Stub::async::ClusterInfo(::grpc::ClientContext* context, const ::rmdb::ClusterInfoReq* request, ::rmdb::ClusterInfoRsp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ClusterInfo_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::rmdb::ClusterInfoRsp>* RmDb::Stub::PrepareAsyncClusterInfoRaw(::grpc::ClientContext* context, const ::rmdb::ClusterInfoReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::rmdb::ClusterInfoRsp, ::rmdb::ClusterInfoReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ClusterInfo_, context, request);
}

::grpc::ClientAsyncResponseReader< ::rmdb::ClusterInfoRsp>* RmDb::Stub::AsyncClusterInfoRaw(::grpc::ClientContext* context, const ::rmdb::ClusterInfoReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncClusterInfoRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status RmDb::Stub::Match(::grpc::ClientContext* context, const ::rmdb::MatchDataReq& request, ::rmdb::MatchDataRsp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::rmdb::MatchDataReq, ::rmdb::MatchDataRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Match_, context, request, response);
}

void RmDb::Stub::async::Match(::grpc::ClientContext* context, const ::rmdb::MatchDataReq* request, ::rmdb::MatchDataRsp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::rmdb::MatchDataReq, ::rmdb::MatchDataRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Match_, context, request, response, std::move(f));
}

void RmDb::Stub::async::Match(::grpc::ClientContext* context, const ::rmdb::MatchDataReq* request, ::rmdb::MatchDataRsp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Match_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::rmdb::MatchDataRsp>* RmDb::Stub::PrepareAsyncMatchRaw(::grpc::ClientContext* context, const ::rmdb::MatchDataReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::rmdb::MatchDataRsp, ::rmdb::MatchDataReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Match_, context, request);
}

::grpc::ClientAsyncResponseReader< ::rmdb::MatchDataRsp>* RmDb::Stub::AsyncMatchRaw(::grpc::ClientContext* context, const ::rmdb::MatchDataReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncMatchRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status RmDb::Stub::Find(::grpc::ClientContext* context, const ::rmdb::FindDataReq& request, ::rmdb::FindDataRsp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::rmdb::FindDataReq, ::rmdb::FindDataRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Find_, context, request, response);
}

void RmDb::Stub::async::Find(::grpc::ClientContext* context, const ::rmdb::FindDataReq* request, ::rmdb::FindDataRsp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::rmdb::FindDataReq, ::rmdb::FindDataRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Find_, context, request, response, std::move(f));
}

void RmDb::Stub::async::Find(::grpc::ClientContext* context, const ::rmdb::FindDataReq* request, ::rmdb::FindDataRsp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Find_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::rmdb::FindDataRsp>* RmDb::Stub::PrepareAsyncFindRaw(::grpc::ClientContext* context, const ::rmdb::FindDataReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::rmdb::FindDataRsp, ::rmdb::FindDataReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Find_, context, request);
}

::grpc::ClientAsyncResponseReader< ::rmdb::FindDataRsp>* RmDb::Stub::AsyncFindRaw(::grpc::ClientContext* context, const ::rmdb::FindDataReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncFindRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status RmDb::Stub::UpdateKey(::grpc::ClientContext* context, const ::rmdb::UpdateKeyReq& request, ::rmdb::UpdateKeyRsp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::rmdb::UpdateKeyReq, ::rmdb::UpdateKeyRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_UpdateKey_, context, request, response);
}

void RmDb::Stub::async::UpdateKey(::grpc::ClientContext* context, const ::rmdb::UpdateKeyReq* request, ::rmdb::UpdateKeyRsp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::rmdb::UpdateKeyReq, ::rmdb::UpdateKeyRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateKey_, context, request, response, std::move(f));
}

void RmDb::Stub::async::UpdateKey(::grpc::ClientContext* context, const ::rmdb::UpdateKeyReq* request, ::rmdb::UpdateKeyRsp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateKey_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::rmdb::UpdateKeyRsp>* RmDb::Stub::PrepareAsyncUpdateKeyRaw(::grpc::ClientContext* context, const ::rmdb::UpdateKeyReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::rmdb::UpdateKeyRsp, ::rmdb::UpdateKeyReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_UpdateKey_, context, request);
}

::grpc::ClientAsyncResponseReader< ::rmdb::UpdateKeyRsp>* RmDb::Stub::AsyncUpdateKeyRaw(::grpc::ClientContext* context, const ::rmdb::UpdateKeyReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncUpdateKeyRaw(context, request, cq);
  result->StartCall();
  return result;
}

RmDb::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RmDb_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RmDb::Service, ::rmdb::SetDataReq, ::rmdb::SetDataRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RmDb::Service* service,
             ::grpc::ServerContext* ctx,
             const ::rmdb::SetDataReq* req,
             ::rmdb::SetDataRsp* resp) {
               return service->Set(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RmDb_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RmDb::Service, ::rmdb::SetNxDataReq, ::rmdb::SetNxDataRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RmDb::Service* service,
             ::grpc::ServerContext* ctx,
             const ::rmdb::SetNxDataReq* req,
             ::rmdb::SetNxDataRsp* resp) {
               return service->SetNx(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RmDb_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RmDb::Service, ::rmdb::GetDataReq, ::rmdb::GetDataRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RmDb::Service* service,
             ::grpc::ServerContext* ctx,
             const ::rmdb::GetDataReq* req,
             ::rmdb::GetDataRsp* resp) {
               return service->Get(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RmDb_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RmDb::Service, ::rmdb::DelDataReq, ::rmdb::DelDataRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RmDb::Service* service,
             ::grpc::ServerContext* ctx,
             const ::rmdb::DelDataReq* req,
             ::rmdb::DelDataRsp* resp) {
               return service->Del(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RmDb_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RmDb::Service, ::rmdb::UpdateDataReq, ::rmdb::UpdateDataRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RmDb::Service* service,
             ::grpc::ServerContext* ctx,
             const ::rmdb::UpdateDataReq* req,
             ::rmdb::UpdateDataRsp* resp) {
               return service->Update(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RmDb_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RmDb::Service, ::rmdb::BatchSetDataReq, ::rmdb::BatchSetDataRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RmDb::Service* service,
             ::grpc::ServerContext* ctx,
             const ::rmdb::BatchSetDataReq* req,
             ::rmdb::BatchSetDataRsp* resp) {
               return service->BatchSet(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RmDb_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RmDb::Service, ::rmdb::BatchSetNxDataReq, ::rmdb::BatchSetNxDataRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RmDb::Service* service,
             ::grpc::ServerContext* ctx,
             const ::rmdb::BatchSetNxDataReq* req,
             ::rmdb::BatchSetNxDataRsp* resp) {
               return service->BatchSetNx(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RmDb_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RmDb::Service, ::rmdb::BatchGetDataReq, ::rmdb::BatchGetDataRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RmDb::Service* service,
             ::grpc::ServerContext* ctx,
             const ::rmdb::BatchGetDataReq* req,
             ::rmdb::BatchGetDataRsp* resp) {
               return service->BatchGet(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RmDb_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RmDb::Service, ::rmdb::BatchDelDataReq, ::rmdb::BatchDelDataRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RmDb::Service* service,
             ::grpc::ServerContext* ctx,
             const ::rmdb::BatchDelDataReq* req,
             ::rmdb::BatchDelDataRsp* resp) {
               return service->BatchDel(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RmDb_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RmDb::Service, ::rmdb::BatchUpdateDataReq, ::rmdb::BatchUpdateDataRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RmDb::Service* service,
             ::grpc::ServerContext* ctx,
             const ::rmdb::BatchUpdateDataReq* req,
             ::rmdb::BatchUpdateDataRsp* resp) {
               return service->BatchUpdate(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RmDb_method_names[10],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RmDb::Service, ::rmdb::GetDataCountReq, ::rmdb::GetDataCountRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RmDb::Service* service,
             ::grpc::ServerContext* ctx,
             const ::rmdb::GetDataCountReq* req,
             ::rmdb::GetDataCountRsp* resp) {
               return service->GetCount(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RmDb_method_names[11],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RmDb::Service, ::rmdb::GetMetaReq, ::rmdb::GetMetaRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RmDb::Service* service,
             ::grpc::ServerContext* ctx,
             const ::rmdb::GetMetaReq* req,
             ::rmdb::GetMetaRsp* resp) {
               return service->GetMeta(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RmDb_method_names[12],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RmDb::Service, ::rmdb::ClusterInfoReq, ::rmdb::ClusterInfoRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RmDb::Service* service,
             ::grpc::ServerContext* ctx,
             const ::rmdb::ClusterInfoReq* req,
             ::rmdb::ClusterInfoRsp* resp) {
               return service->ClusterInfo(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RmDb_method_names[13],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RmDb::Service, ::rmdb::MatchDataReq, ::rmdb::MatchDataRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RmDb::Service* service,
             ::grpc::ServerContext* ctx,
             const ::rmdb::MatchDataReq* req,
             ::rmdb::MatchDataRsp* resp) {
               return service->Match(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RmDb_method_names[14],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RmDb::Service, ::rmdb::FindDataReq, ::rmdb::FindDataRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RmDb::Service* service,
             ::grpc::ServerContext* ctx,
             const ::rmdb::FindDataReq* req,
             ::rmdb::FindDataRsp* resp) {
               return service->Find(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RmDb_method_names[15],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RmDb::Service, ::rmdb::UpdateKeyReq, ::rmdb::UpdateKeyRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RmDb::Service* service,
             ::grpc::ServerContext* ctx,
             const ::rmdb::UpdateKeyReq* req,
             ::rmdb::UpdateKeyRsp* resp) {
               return service->UpdateKey(ctx, req, resp);
             }, this)));
}

RmDb::Service::~Service() {
}

::grpc::Status RmDb::Service::Set(::grpc::ServerContext* context, const ::rmdb::SetDataReq* request, ::rmdb::SetDataRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RmDb::Service::SetNx(::grpc::ServerContext* context, const ::rmdb::SetNxDataReq* request, ::rmdb::SetNxDataRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RmDb::Service::Get(::grpc::ServerContext* context, const ::rmdb::GetDataReq* request, ::rmdb::GetDataRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RmDb::Service::Del(::grpc::ServerContext* context, const ::rmdb::DelDataReq* request, ::rmdb::DelDataRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RmDb::Service::Update(::grpc::ServerContext* context, const ::rmdb::UpdateDataReq* request, ::rmdb::UpdateDataRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RmDb::Service::BatchSet(::grpc::ServerContext* context, const ::rmdb::BatchSetDataReq* request, ::rmdb::BatchSetDataRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RmDb::Service::BatchSetNx(::grpc::ServerContext* context, const ::rmdb::BatchSetNxDataReq* request, ::rmdb::BatchSetNxDataRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RmDb::Service::BatchGet(::grpc::ServerContext* context, const ::rmdb::BatchGetDataReq* request, ::rmdb::BatchGetDataRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RmDb::Service::BatchDel(::grpc::ServerContext* context, const ::rmdb::BatchDelDataReq* request, ::rmdb::BatchDelDataRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RmDb::Service::BatchUpdate(::grpc::ServerContext* context, const ::rmdb::BatchUpdateDataReq* request, ::rmdb::BatchUpdateDataRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RmDb::Service::GetCount(::grpc::ServerContext* context, const ::rmdb::GetDataCountReq* request, ::rmdb::GetDataCountRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RmDb::Service::GetMeta(::grpc::ServerContext* context, const ::rmdb::GetMetaReq* request, ::rmdb::GetMetaRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RmDb::Service::ClusterInfo(::grpc::ServerContext* context, const ::rmdb::ClusterInfoReq* request, ::rmdb::ClusterInfoRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RmDb::Service::Match(::grpc::ServerContext* context, const ::rmdb::MatchDataReq* request, ::rmdb::MatchDataRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RmDb::Service::Find(::grpc::ServerContext* context, const ::rmdb::FindDataReq* request, ::rmdb::FindDataRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RmDb::Service::UpdateKey(::grpc::ServerContext* context, const ::rmdb::UpdateKeyReq* request, ::rmdb::UpdateKeyRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace rmdb

