// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cpp/ErrorCodeKit.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_cpp_2fErrorCodeKit_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_cpp_2fErrorCodeKit_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4023000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4023001 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_cpp_2fErrorCodeKit_2eproto

PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_cpp_2fErrorCodeKit_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable
    descriptor_table_cpp_2fErrorCodeKit_2eproto;
namespace sheetcfg {
class ErrorCodeKit;
struct ErrorCodeKitDefaultTypeInternal;
extern ErrorCodeKitDefaultTypeInternal _ErrorCodeKit_default_instance_;
class ErrorCodeKitSheet;
struct ErrorCodeKitSheetDefaultTypeInternal;
extern ErrorCodeKitSheetDefaultTypeInternal _ErrorCodeKitSheet_default_instance_;
}  // namespace sheetcfg
PROTOBUF_NAMESPACE_OPEN
template <>
::sheetcfg::ErrorCodeKit* Arena::CreateMaybeMessage<::sheetcfg::ErrorCodeKit>(Arena*);
template <>
::sheetcfg::ErrorCodeKitSheet* Arena::CreateMaybeMessage<::sheetcfg::ErrorCodeKitSheet>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

namespace sheetcfg {

// ===================================================================


// -------------------------------------------------------------------

class ErrorCodeKit final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sheetcfg.ErrorCodeKit) */ {
 public:
  inline ErrorCodeKit() : ErrorCodeKit(nullptr) {}
  ~ErrorCodeKit() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR ErrorCodeKit(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ErrorCodeKit(const ErrorCodeKit& from);
  ErrorCodeKit(ErrorCodeKit&& from) noexcept
    : ErrorCodeKit() {
    *this = ::std::move(from);
  }

  inline ErrorCodeKit& operator=(const ErrorCodeKit& from) {
    CopyFrom(from);
    return *this;
  }
  inline ErrorCodeKit& operator=(ErrorCodeKit&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ErrorCodeKit& default_instance() {
    return *internal_default_instance();
  }
  static inline const ErrorCodeKit* internal_default_instance() {
    return reinterpret_cast<const ErrorCodeKit*>(
               &_ErrorCodeKit_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ErrorCodeKit& a, ErrorCodeKit& b) {
    a.Swap(&b);
  }
  inline void Swap(ErrorCodeKit* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ErrorCodeKit* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ErrorCodeKit* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ErrorCodeKit>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ErrorCodeKit& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ErrorCodeKit& from) {
    ErrorCodeKit::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ErrorCodeKit* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "sheetcfg.ErrorCodeKit";
  }
  protected:
  explicit ErrorCodeKit(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kArrContentFieldNumber = 2,
    kIdFieldNumber = 1,
  };
  // repeated string ArrContent = 2;
  int arrcontent_size() const;
  private:
  int _internal_arrcontent_size() const;

  public:
  void clear_arrcontent() ;
  const std::string& arrcontent(int index) const;
  std::string* mutable_arrcontent(int index);
  void set_arrcontent(int index, const std::string& value);
  void set_arrcontent(int index, std::string&& value);
  void set_arrcontent(int index, const char* value);
  void set_arrcontent(int index, const char* value, std::size_t size);
  void set_arrcontent(int index, absl::string_view value);
  std::string* add_arrcontent();
  void add_arrcontent(const std::string& value);
  void add_arrcontent(std::string&& value);
  void add_arrcontent(const char* value);
  void add_arrcontent(const char* value, std::size_t size);
  void add_arrcontent(absl::string_view value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& arrcontent() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_arrcontent();

  private:
  const std::string& _internal_arrcontent(int index) const;
  std::string* _internal_add_arrcontent();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& _internal_arrcontent() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* _internal_mutable_arrcontent();

  public:
  // int64 Id = 1;
  void clear_id() ;
  ::int64_t id() const;
  void set_id(::int64_t value);

  private:
  ::int64_t _internal_id() const;
  void _internal_set_id(::int64_t value);

  public:
  // @@protoc_insertion_point(class_scope:sheetcfg.ErrorCodeKit)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> arrcontent_;
    ::int64_t id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_cpp_2fErrorCodeKit_2eproto;
};// -------------------------------------------------------------------

class ErrorCodeKitSheet final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sheetcfg.ErrorCodeKitSheet) */ {
 public:
  inline ErrorCodeKitSheet() : ErrorCodeKitSheet(nullptr) {}
  ~ErrorCodeKitSheet() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR ErrorCodeKitSheet(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ErrorCodeKitSheet(const ErrorCodeKitSheet& from);
  ErrorCodeKitSheet(ErrorCodeKitSheet&& from) noexcept
    : ErrorCodeKitSheet() {
    *this = ::std::move(from);
  }

  inline ErrorCodeKitSheet& operator=(const ErrorCodeKitSheet& from) {
    CopyFrom(from);
    return *this;
  }
  inline ErrorCodeKitSheet& operator=(ErrorCodeKitSheet&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ErrorCodeKitSheet& default_instance() {
    return *internal_default_instance();
  }
  static inline const ErrorCodeKitSheet* internal_default_instance() {
    return reinterpret_cast<const ErrorCodeKitSheet*>(
               &_ErrorCodeKitSheet_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ErrorCodeKitSheet& a, ErrorCodeKitSheet& b) {
    a.Swap(&b);
  }
  inline void Swap(ErrorCodeKitSheet* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ErrorCodeKitSheet* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ErrorCodeKitSheet* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ErrorCodeKitSheet>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ErrorCodeKitSheet& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ErrorCodeKitSheet& from) {
    ErrorCodeKitSheet::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ErrorCodeKitSheet* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "sheetcfg.ErrorCodeKitSheet";
  }
  protected:
  explicit ErrorCodeKitSheet(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kItemsFieldNumber = 1,
  };
  // repeated .sheetcfg.ErrorCodeKit items = 1;
  int items_size() const;
  private:
  int _internal_items_size() const;

  public:
  void clear_items() ;
  ::sheetcfg::ErrorCodeKit* mutable_items(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::sheetcfg::ErrorCodeKit >*
      mutable_items();
  private:
  const ::sheetcfg::ErrorCodeKit& _internal_items(int index) const;
  ::sheetcfg::ErrorCodeKit* _internal_add_items();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<::sheetcfg::ErrorCodeKit>& _internal_items() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<::sheetcfg::ErrorCodeKit>* _internal_mutable_items();
  public:
  const ::sheetcfg::ErrorCodeKit& items(int index) const;
  ::sheetcfg::ErrorCodeKit* add_items();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::sheetcfg::ErrorCodeKit >&
      items() const;
  // @@protoc_insertion_point(class_scope:sheetcfg.ErrorCodeKitSheet)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::sheetcfg::ErrorCodeKit > items_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_cpp_2fErrorCodeKit_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ErrorCodeKit

// int64 Id = 1;
inline void ErrorCodeKit::clear_id() {
  _impl_.id_ = ::int64_t{0};
}
inline ::int64_t ErrorCodeKit::id() const {
  // @@protoc_insertion_point(field_get:sheetcfg.ErrorCodeKit.Id)
  return _internal_id();
}
inline void ErrorCodeKit::set_id(::int64_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:sheetcfg.ErrorCodeKit.Id)
}
inline ::int64_t ErrorCodeKit::_internal_id() const {
  return _impl_.id_;
}
inline void ErrorCodeKit::_internal_set_id(::int64_t value) {
  ;
  _impl_.id_ = value;
}

// repeated string ArrContent = 2;
inline int ErrorCodeKit::_internal_arrcontent_size() const {
  return _impl_.arrcontent_.size();
}
inline int ErrorCodeKit::arrcontent_size() const {
  return _internal_arrcontent_size();
}
inline void ErrorCodeKit::clear_arrcontent() {
  _internal_mutable_arrcontent()->Clear();
}
inline std::string* ErrorCodeKit::add_arrcontent() {
  std::string* _s = _internal_add_arrcontent();
  // @@protoc_insertion_point(field_add_mutable:sheetcfg.ErrorCodeKit.ArrContent)
  return _s;
}
inline const std::string& ErrorCodeKit::arrcontent(int index) const {
  // @@protoc_insertion_point(field_get:sheetcfg.ErrorCodeKit.ArrContent)
  return _internal_arrcontent(index);
}
inline std::string* ErrorCodeKit::mutable_arrcontent(int index) {
  // @@protoc_insertion_point(field_mutable:sheetcfg.ErrorCodeKit.ArrContent)
  return _internal_mutable_arrcontent()->Mutable(index);
}
inline void ErrorCodeKit::set_arrcontent(int index, const std::string& value) {
  _internal_mutable_arrcontent()->Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:sheetcfg.ErrorCodeKit.ArrContent)
}
inline void ErrorCodeKit::set_arrcontent(int index, std::string&& value) {
  _internal_mutable_arrcontent()->Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:sheetcfg.ErrorCodeKit.ArrContent)
}
inline void ErrorCodeKit::set_arrcontent(int index, const char* value) {
  ABSL_DCHECK(value != nullptr);
  _internal_mutable_arrcontent()->Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:sheetcfg.ErrorCodeKit.ArrContent)
}
inline void ErrorCodeKit::set_arrcontent(int index, const char* value,
                              std::size_t size) {
  _internal_mutable_arrcontent()->Mutable(index)->assign(
      reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:sheetcfg.ErrorCodeKit.ArrContent)
}
inline void ErrorCodeKit::set_arrcontent(int index, absl::string_view value) {
  _internal_mutable_arrcontent()->Mutable(index)->assign(value.data(),
                                                     value.size());
  // @@protoc_insertion_point(field_set_string_piece:sheetcfg.ErrorCodeKit.ArrContent)
}
inline void ErrorCodeKit::add_arrcontent(const std::string& value) {
  _internal_mutable_arrcontent()->Add()->assign(value);
  // @@protoc_insertion_point(field_add:sheetcfg.ErrorCodeKit.ArrContent)
}
inline void ErrorCodeKit::add_arrcontent(std::string&& value) {
  _internal_mutable_arrcontent()->Add(std::move(value));
  // @@protoc_insertion_point(field_add:sheetcfg.ErrorCodeKit.ArrContent)
}
inline void ErrorCodeKit::add_arrcontent(const char* value) {
  ABSL_DCHECK(value != nullptr);
  _internal_mutable_arrcontent()->Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:sheetcfg.ErrorCodeKit.ArrContent)
}
inline void ErrorCodeKit::add_arrcontent(const char* value, std::size_t size) {
  _internal_mutable_arrcontent()->Add()->assign(
      reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:sheetcfg.ErrorCodeKit.ArrContent)
}
inline void ErrorCodeKit::add_arrcontent(absl::string_view value) {
  _internal_mutable_arrcontent()->Add()->assign(value.data(), value.size());
  // @@protoc_insertion_point(field_add_string_piece:sheetcfg.ErrorCodeKit.ArrContent)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
ErrorCodeKit::arrcontent() const {
  // @@protoc_insertion_point(field_list:sheetcfg.ErrorCodeKit.ArrContent)
  return _internal_arrcontent();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* ErrorCodeKit::mutable_arrcontent() {
  // @@protoc_insertion_point(field_mutable_list:sheetcfg.ErrorCodeKit.ArrContent)
  return _internal_mutable_arrcontent();
}
inline const std::string& ErrorCodeKit::_internal_arrcontent(int index) const {
  return _internal_arrcontent().Get(index);
}
inline std::string* ErrorCodeKit::_internal_add_arrcontent() {
  return _internal_mutable_arrcontent()->Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
ErrorCodeKit::_internal_arrcontent() const {
  return _impl_.arrcontent_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
ErrorCodeKit::_internal_mutable_arrcontent() {
  return &_impl_.arrcontent_;
}

// -------------------------------------------------------------------

// ErrorCodeKitSheet

// repeated .sheetcfg.ErrorCodeKit items = 1;
inline int ErrorCodeKitSheet::_internal_items_size() const {
  return _impl_.items_.size();
}
inline int ErrorCodeKitSheet::items_size() const {
  return _internal_items_size();
}
inline void ErrorCodeKitSheet::clear_items() {
  _internal_mutable_items()->Clear();
}
inline ::sheetcfg::ErrorCodeKit* ErrorCodeKitSheet::mutable_items(int index) {
  // @@protoc_insertion_point(field_mutable:sheetcfg.ErrorCodeKitSheet.items)
  return _internal_mutable_items()->Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::sheetcfg::ErrorCodeKit >*
ErrorCodeKitSheet::mutable_items() {
  // @@protoc_insertion_point(field_mutable_list:sheetcfg.ErrorCodeKitSheet.items)
  return _internal_mutable_items();
}
inline const ::sheetcfg::ErrorCodeKit& ErrorCodeKitSheet::_internal_items(int index) const {
  return _internal_items().Get(index);
}
inline const ::sheetcfg::ErrorCodeKit& ErrorCodeKitSheet::items(int index) const {
  // @@protoc_insertion_point(field_get:sheetcfg.ErrorCodeKitSheet.items)
  return _internal_items(index);
}
inline ::sheetcfg::ErrorCodeKit* ErrorCodeKitSheet::_internal_add_items() {
  return _internal_mutable_items()->Add();
}
inline ::sheetcfg::ErrorCodeKit* ErrorCodeKitSheet::add_items() {
  ::sheetcfg::ErrorCodeKit* _add = _internal_add_items();
  // @@protoc_insertion_point(field_add:sheetcfg.ErrorCodeKitSheet.items)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::sheetcfg::ErrorCodeKit >&
ErrorCodeKitSheet::items() const {
  // @@protoc_insertion_point(field_list:sheetcfg.ErrorCodeKitSheet.items)
  return _internal_items();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<::sheetcfg::ErrorCodeKit>&
ErrorCodeKitSheet::_internal_items() const {
  return _impl_.items_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<::sheetcfg::ErrorCodeKit>*
ErrorCodeKitSheet::_internal_mutable_items() {
  return &_impl_.items_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace sheetcfg


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_cpp_2fErrorCodeKit_2eproto_2epb_2eh
