// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cpp/sheet.proto

#include "cpp/sheet.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = ::PROTOBUF_NAMESPACE_ID::internal;
namespace sheetcfg {
template <typename>
PROTOBUF_CONSTEXPR AITemperamentConfig::AITemperamentConfig(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.id_)*/ ::int64_t{0}

  , /*decltype(_impl_.nameid_)*/ ::int64_t{0}

  , /*decltype(_impl_._cached_size_)*/{}} {}
struct AITemperamentConfigDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AITemperamentConfigDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AITemperamentConfigDefaultTypeInternal() {}
  union {
    AITemperamentConfig _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AITemperamentConfigDefaultTypeInternal _AITemperamentConfig_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR AITemperamentConfigSheet::AITemperamentConfigSheet(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.items_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct AITemperamentConfigSheetDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AITemperamentConfigSheetDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AITemperamentConfigSheetDefaultTypeInternal() {}
  union {
    AITemperamentConfigSheet _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AITemperamentConfigSheetDefaultTypeInternal _AITemperamentConfigSheet_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR ErrorCodeKit::ErrorCodeKit(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.arrcontent_)*/{}
  , /*decltype(_impl_.id_)*/ ::int64_t{0}

  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ErrorCodeKitDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ErrorCodeKitDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ErrorCodeKitDefaultTypeInternal() {}
  union {
    ErrorCodeKit _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ErrorCodeKitDefaultTypeInternal _ErrorCodeKit_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR ErrorCodeKitSheet::ErrorCodeKitSheet(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.items_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ErrorCodeKitSheetDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ErrorCodeKitSheetDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ErrorCodeKitSheetDefaultTypeInternal() {}
  union {
    ErrorCodeKitSheet _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ErrorCodeKitSheetDefaultTypeInternal _ErrorCodeKitSheet_default_instance_;
}  // namespace sheetcfg
static ::_pb::Metadata file_level_metadata_cpp_2fsheet_2eproto[4];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_cpp_2fsheet_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_cpp_2fsheet_2eproto = nullptr;
const ::uint32_t TableStruct_cpp_2fsheet_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::sheetcfg::AITemperamentConfig, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::sheetcfg::AITemperamentConfig, _impl_.id_),
    PROTOBUF_FIELD_OFFSET(::sheetcfg::AITemperamentConfig, _impl_.nameid_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::sheetcfg::AITemperamentConfigSheet, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::sheetcfg::AITemperamentConfigSheet, _impl_.items_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::sheetcfg::ErrorCodeKit, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::sheetcfg::ErrorCodeKit, _impl_.id_),
    PROTOBUF_FIELD_OFFSET(::sheetcfg::ErrorCodeKit, _impl_.arrcontent_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::sheetcfg::ErrorCodeKitSheet, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::sheetcfg::ErrorCodeKitSheet, _impl_.items_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        { 0, -1, -1, sizeof(::sheetcfg::AITemperamentConfig)},
        { 10, -1, -1, sizeof(::sheetcfg::AITemperamentConfigSheet)},
        { 19, -1, -1, sizeof(::sheetcfg::ErrorCodeKit)},
        { 29, -1, -1, sizeof(::sheetcfg::ErrorCodeKitSheet)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::sheetcfg::_AITemperamentConfig_default_instance_._instance,
    &::sheetcfg::_AITemperamentConfigSheet_default_instance_._instance,
    &::sheetcfg::_ErrorCodeKit_default_instance_._instance,
    &::sheetcfg::_ErrorCodeKitSheet_default_instance_._instance,
};
const char descriptor_table_protodef_cpp_2fsheet_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\017cpp/sheet.proto\022\010sheetcfg\"1\n\023AITempera"
    "mentConfig\022\n\n\002Id\030\001 \001(\003\022\016\n\006NameID\030\002 \001(\003\"H"
    "\n\030AITemperamentConfigSheet\022,\n\005items\030\001 \003("
    "\0132\035.sheetcfg.AITemperamentConfig\".\n\014Erro"
    "rCodeKit\022\n\n\002Id\030\001 \001(\003\022\022\n\nArrContent\030\002 \003(\t"
    "\":\n\021ErrorCodeKitSheet\022%\n\005items\030\001 \003(\0132\026.s"
    "heetcfg.ErrorCodeKitb\006proto3"
};
static ::absl::once_flag descriptor_table_cpp_2fsheet_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_cpp_2fsheet_2eproto = {
    false,
    false,
    268,
    descriptor_table_protodef_cpp_2fsheet_2eproto,
    "cpp/sheet.proto",
    &descriptor_table_cpp_2fsheet_2eproto_once,
    nullptr,
    0,
    4,
    schemas,
    file_default_instances,
    TableStruct_cpp_2fsheet_2eproto::offsets,
    file_level_metadata_cpp_2fsheet_2eproto,
    file_level_enum_descriptors_cpp_2fsheet_2eproto,
    file_level_service_descriptors_cpp_2fsheet_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_cpp_2fsheet_2eproto_getter() {
  return &descriptor_table_cpp_2fsheet_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_cpp_2fsheet_2eproto(&descriptor_table_cpp_2fsheet_2eproto);
namespace sheetcfg {
// ===================================================================

class AITemperamentConfig::_Internal {
 public:
};

AITemperamentConfig::AITemperamentConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:sheetcfg.AITemperamentConfig)
}
AITemperamentConfig::AITemperamentConfig(const AITemperamentConfig& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(), _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(
      from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:sheetcfg.AITemperamentConfig)
}

inline void AITemperamentConfig::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.id_) { ::int64_t{0} }

    , decltype(_impl_.nameid_) { ::int64_t{0} }

    , /*decltype(_impl_._cached_size_)*/{}
  };
}

AITemperamentConfig::~AITemperamentConfig() {
  // @@protoc_insertion_point(destructor:sheetcfg.AITemperamentConfig)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void AITemperamentConfig::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
}

void AITemperamentConfig::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void AITemperamentConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:sheetcfg.AITemperamentConfig)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.nameid_) -
      reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.nameid_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AITemperamentConfig::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 Id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 8)) {
          _impl_.id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // int64 NameID = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 16)) {
          _impl_.nameid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* AITemperamentConfig::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:sheetcfg.AITemperamentConfig)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 Id = 1;
  if (this->_internal_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(
        1, this->_internal_id(), target);
  }

  // int64 NameID = 2;
  if (this->_internal_nameid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(
        2, this->_internal_nameid(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sheetcfg.AITemperamentConfig)
  return target;
}

::size_t AITemperamentConfig::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sheetcfg.AITemperamentConfig)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 Id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_id());
  }

  // int64 NameID = 2;
  if (this->_internal_nameid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_nameid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData AITemperamentConfig::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    AITemperamentConfig::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*AITemperamentConfig::GetClassData() const { return &_class_data_; }


void AITemperamentConfig::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<AITemperamentConfig*>(&to_msg);
  auto& from = static_cast<const AITemperamentConfig&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:sheetcfg.AITemperamentConfig)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  if (from._internal_nameid() != 0) {
    _this->_internal_set_nameid(from._internal_nameid());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void AITemperamentConfig::CopyFrom(const AITemperamentConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sheetcfg.AITemperamentConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AITemperamentConfig::IsInitialized() const {
  return true;
}

void AITemperamentConfig::InternalSwap(AITemperamentConfig* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(AITemperamentConfig, _impl_.nameid_)
      + sizeof(AITemperamentConfig::_impl_.nameid_)
      - PROTOBUF_FIELD_OFFSET(AITemperamentConfig, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata AITemperamentConfig::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_cpp_2fsheet_2eproto_getter, &descriptor_table_cpp_2fsheet_2eproto_once,
      file_level_metadata_cpp_2fsheet_2eproto[0]);
}
// ===================================================================

class AITemperamentConfigSheet::_Internal {
 public:
};

AITemperamentConfigSheet::AITemperamentConfigSheet(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:sheetcfg.AITemperamentConfigSheet)
}
AITemperamentConfigSheet::AITemperamentConfigSheet(const AITemperamentConfigSheet& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  AITemperamentConfigSheet* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.items_){from._impl_.items_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:sheetcfg.AITemperamentConfigSheet)
}

inline void AITemperamentConfigSheet::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.items_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

AITemperamentConfigSheet::~AITemperamentConfigSheet() {
  // @@protoc_insertion_point(destructor:sheetcfg.AITemperamentConfigSheet)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void AITemperamentConfigSheet::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _internal_mutable_items()->~RepeatedPtrField();
}

void AITemperamentConfigSheet::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void AITemperamentConfigSheet::Clear() {
// @@protoc_insertion_point(message_clear_start:sheetcfg.AITemperamentConfigSheet)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_mutable_items()->Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AITemperamentConfigSheet::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .sheetcfg.AITemperamentConfig items = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_items(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* AITemperamentConfigSheet::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:sheetcfg.AITemperamentConfigSheet)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .sheetcfg.AITemperamentConfig items = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_items_size()); i < n; i++) {
    const auto& repfield = this->_internal_items(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sheetcfg.AITemperamentConfigSheet)
  return target;
}

::size_t AITemperamentConfigSheet::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sheetcfg.AITemperamentConfigSheet)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .sheetcfg.AITemperamentConfig items = 1;
  total_size += 1UL * this->_internal_items_size();
  for (const auto& msg : this->_internal_items()) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData AITemperamentConfigSheet::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    AITemperamentConfigSheet::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*AITemperamentConfigSheet::GetClassData() const { return &_class_data_; }


void AITemperamentConfigSheet::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<AITemperamentConfigSheet*>(&to_msg);
  auto& from = static_cast<const AITemperamentConfigSheet&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:sheetcfg.AITemperamentConfigSheet)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_items()->MergeFrom(from._internal_items());
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void AITemperamentConfigSheet::CopyFrom(const AITemperamentConfigSheet& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sheetcfg.AITemperamentConfigSheet)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AITemperamentConfigSheet::IsInitialized() const {
  return true;
}

void AITemperamentConfigSheet::InternalSwap(AITemperamentConfigSheet* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _internal_mutable_items()->InternalSwap(other->_internal_mutable_items());
}

::PROTOBUF_NAMESPACE_ID::Metadata AITemperamentConfigSheet::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_cpp_2fsheet_2eproto_getter, &descriptor_table_cpp_2fsheet_2eproto_once,
      file_level_metadata_cpp_2fsheet_2eproto[1]);
}
// ===================================================================

class ErrorCodeKit::_Internal {
 public:
};

ErrorCodeKit::ErrorCodeKit(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:sheetcfg.ErrorCodeKit)
}
ErrorCodeKit::ErrorCodeKit(const ErrorCodeKit& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ErrorCodeKit* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.arrcontent_){from._impl_.arrcontent_}
    , decltype(_impl_.id_) {}

    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.id_ = from._impl_.id_;
  // @@protoc_insertion_point(copy_constructor:sheetcfg.ErrorCodeKit)
}

inline void ErrorCodeKit::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.arrcontent_){arena}
    , decltype(_impl_.id_) { ::int64_t{0} }

    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ErrorCodeKit::~ErrorCodeKit() {
  // @@protoc_insertion_point(destructor:sheetcfg.ErrorCodeKit)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ErrorCodeKit::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _internal_mutable_arrcontent()->~RepeatedPtrField();
}

void ErrorCodeKit::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ErrorCodeKit::Clear() {
// @@protoc_insertion_point(message_clear_start:sheetcfg.ErrorCodeKit)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_mutable_arrcontent()->Clear();
  _impl_.id_ = ::int64_t{0};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ErrorCodeKit::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 Id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 8)) {
          _impl_.id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // repeated string ArrContent = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_arrcontent();
            ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            CHK_(::_pbi::VerifyUTF8(str, "sheetcfg.ErrorCodeKit.ArrContent"));
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* ErrorCodeKit::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:sheetcfg.ErrorCodeKit)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 Id = 1;
  if (this->_internal_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(
        1, this->_internal_id(), target);
  }

  // repeated string ArrContent = 2;
  for (int i = 0, n = this->_internal_arrcontent_size(); i < n; ++i) {
    const auto& s = this->_internal_arrcontent(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        s.data(), static_cast<int>(s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "sheetcfg.ErrorCodeKit.ArrContent");
    target = stream->WriteString(2, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sheetcfg.ErrorCodeKit)
  return target;
}

::size_t ErrorCodeKit::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sheetcfg.ErrorCodeKit)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string ArrContent = 2;
  total_size += 1 * ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(_internal_arrcontent().size());
  for (int i = 0, n = _internal_arrcontent().size(); i < n; ++i) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        _internal_arrcontent().Get(i));
  }

  // int64 Id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ErrorCodeKit::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ErrorCodeKit::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ErrorCodeKit::GetClassData() const { return &_class_data_; }


void ErrorCodeKit::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ErrorCodeKit*>(&to_msg);
  auto& from = static_cast<const ErrorCodeKit&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:sheetcfg.ErrorCodeKit)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_arrcontent()->MergeFrom(from._internal_arrcontent());
  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ErrorCodeKit::CopyFrom(const ErrorCodeKit& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sheetcfg.ErrorCodeKit)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ErrorCodeKit::IsInitialized() const {
  return true;
}

void ErrorCodeKit::InternalSwap(ErrorCodeKit* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _internal_mutable_arrcontent()->InternalSwap(
      other->_internal_mutable_arrcontent());

  swap(_impl_.id_, other->_impl_.id_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ErrorCodeKit::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_cpp_2fsheet_2eproto_getter, &descriptor_table_cpp_2fsheet_2eproto_once,
      file_level_metadata_cpp_2fsheet_2eproto[2]);
}
// ===================================================================

class ErrorCodeKitSheet::_Internal {
 public:
};

ErrorCodeKitSheet::ErrorCodeKitSheet(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:sheetcfg.ErrorCodeKitSheet)
}
ErrorCodeKitSheet::ErrorCodeKitSheet(const ErrorCodeKitSheet& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ErrorCodeKitSheet* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.items_){from._impl_.items_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:sheetcfg.ErrorCodeKitSheet)
}

inline void ErrorCodeKitSheet::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.items_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ErrorCodeKitSheet::~ErrorCodeKitSheet() {
  // @@protoc_insertion_point(destructor:sheetcfg.ErrorCodeKitSheet)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ErrorCodeKitSheet::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _internal_mutable_items()->~RepeatedPtrField();
}

void ErrorCodeKitSheet::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ErrorCodeKitSheet::Clear() {
// @@protoc_insertion_point(message_clear_start:sheetcfg.ErrorCodeKitSheet)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_mutable_items()->Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ErrorCodeKitSheet::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .sheetcfg.ErrorCodeKit items = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_items(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* ErrorCodeKitSheet::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:sheetcfg.ErrorCodeKitSheet)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .sheetcfg.ErrorCodeKit items = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_items_size()); i < n; i++) {
    const auto& repfield = this->_internal_items(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sheetcfg.ErrorCodeKitSheet)
  return target;
}

::size_t ErrorCodeKitSheet::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sheetcfg.ErrorCodeKitSheet)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .sheetcfg.ErrorCodeKit items = 1;
  total_size += 1UL * this->_internal_items_size();
  for (const auto& msg : this->_internal_items()) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ErrorCodeKitSheet::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ErrorCodeKitSheet::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ErrorCodeKitSheet::GetClassData() const { return &_class_data_; }


void ErrorCodeKitSheet::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ErrorCodeKitSheet*>(&to_msg);
  auto& from = static_cast<const ErrorCodeKitSheet&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:sheetcfg.ErrorCodeKitSheet)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_items()->MergeFrom(from._internal_items());
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ErrorCodeKitSheet::CopyFrom(const ErrorCodeKitSheet& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sheetcfg.ErrorCodeKitSheet)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ErrorCodeKitSheet::IsInitialized() const {
  return true;
}

void ErrorCodeKitSheet::InternalSwap(ErrorCodeKitSheet* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _internal_mutable_items()->InternalSwap(other->_internal_mutable_items());
}

::PROTOBUF_NAMESPACE_ID::Metadata ErrorCodeKitSheet::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_cpp_2fsheet_2eproto_getter, &descriptor_table_cpp_2fsheet_2eproto_once,
      file_level_metadata_cpp_2fsheet_2eproto[3]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace sheetcfg
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::sheetcfg::AITemperamentConfig*
Arena::CreateMaybeMessage< ::sheetcfg::AITemperamentConfig >(Arena* arena) {
  return Arena::CreateMessageInternal< ::sheetcfg::AITemperamentConfig >(arena);
}
template<> PROTOBUF_NOINLINE ::sheetcfg::AITemperamentConfigSheet*
Arena::CreateMaybeMessage< ::sheetcfg::AITemperamentConfigSheet >(Arena* arena) {
  return Arena::CreateMessageInternal< ::sheetcfg::AITemperamentConfigSheet >(arena);
}
template<> PROTOBUF_NOINLINE ::sheetcfg::ErrorCodeKit*
Arena::CreateMaybeMessage< ::sheetcfg::ErrorCodeKit >(Arena* arena) {
  return Arena::CreateMessageInternal< ::sheetcfg::ErrorCodeKit >(arena);
}
template<> PROTOBUF_NOINLINE ::sheetcfg::ErrorCodeKitSheet*
Arena::CreateMaybeMessage< ::sheetcfg::ErrorCodeKitSheet >(Arena* arena) {
  return Arena::CreateMessageInternal< ::sheetcfg::ErrorCodeKitSheet >(arena);
}
PROTOBUF_NAMESPACE_CLOSE
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
