syntax = "proto3";
package sheetcfg;

// 文件生成时间: 2024-03-08 12:08:40.6441154 +0800 CST m=+0.010312801
// AI性格表.xlsx => [AITemperamentConfig].sheet
message AITemperamentConfig {
  int64 Id = 1; // id 
  int64 NameID = 2; // 性格名对应的表id 
}
message AITemperamentConfigSheet {
  repeated AITemperamentConfig items = 1;
}

// 文件生成时间: 2024-03-08 12:08:40.6441154 +0800 CST m=+0.010312801
// c错误码文本.xlsx => [ErrorCodeKit].sheet
message ErrorCodeKit {
  int64 Id = 1; // 编码 
  repeated string ArrContent = 2; // 简体中文 
}
message ErrorCodeKitSheet {
  repeated ErrorCodeKit items = 1;
}

