// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: helloworld.proto

#include "helloworld.pb.h"
#include "helloworld.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace helloworld {

static const char* Greeter_method_names[] = {
  "/helloworld.Greeter/SayHello",
  "/helloworld.Greeter/GetName",
  "/helloworld.Greeter/ListName",
  "/helloworld.Greeter/ClientStreamSayHello",
  "/helloworld.Greeter/ServerStreamSayHello",
};

std::unique_ptr< Greeter::Stub> Greeter::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Greeter::Stub> stub(new Greeter::Stub(channel, options));
  return stub;
}

Greeter::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SayHello_(Greeter_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetName_(Greeter_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListName_(Greeter_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  , rpcmethod_ClientStreamSayHello_(Greeter_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::CLIENT_STREAMING, channel)
  , rpcmethod_ServerStreamSayHello_(Greeter_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::Status Greeter::Stub::SayHello(::grpc::ClientContext* context, const ::helloworld::HelloRequest& request, ::helloworld::HelloReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::helloworld::HelloRequest, ::helloworld::HelloReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SayHello_, context, request, response);
}

void Greeter::Stub::async::SayHello(::grpc::ClientContext* context, const ::helloworld::HelloRequest* request, ::helloworld::HelloReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::helloworld::HelloRequest, ::helloworld::HelloReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SayHello_, context, request, response, std::move(f));
}

void Greeter::Stub::async::SayHello(::grpc::ClientContext* context, const ::helloworld::HelloRequest* request, ::helloworld::HelloReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SayHello_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::helloworld::HelloReply>* Greeter::Stub::PrepareAsyncSayHelloRaw(::grpc::ClientContext* context, const ::helloworld::HelloRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::helloworld::HelloReply, ::helloworld::HelloRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SayHello_, context, request);
}

::grpc::ClientAsyncResponseReader< ::helloworld::HelloReply>* Greeter::Stub::AsyncSayHelloRaw(::grpc::ClientContext* context, const ::helloworld::HelloRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSayHelloRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Greeter::Stub::GetName(::grpc::ClientContext* context, const ::helloworld::FamilyRequest& request, ::helloworld::FamilyResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::helloworld::FamilyRequest, ::helloworld::FamilyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetName_, context, request, response);
}

void Greeter::Stub::async::GetName(::grpc::ClientContext* context, const ::helloworld::FamilyRequest* request, ::helloworld::FamilyResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::helloworld::FamilyRequest, ::helloworld::FamilyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetName_, context, request, response, std::move(f));
}

void Greeter::Stub::async::GetName(::grpc::ClientContext* context, const ::helloworld::FamilyRequest* request, ::helloworld::FamilyResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetName_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::helloworld::FamilyResponse>* Greeter::Stub::PrepareAsyncGetNameRaw(::grpc::ClientContext* context, const ::helloworld::FamilyRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::helloworld::FamilyResponse, ::helloworld::FamilyRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetName_, context, request);
}

::grpc::ClientAsyncResponseReader< ::helloworld::FamilyResponse>* Greeter::Stub::AsyncGetNameRaw(::grpc::ClientContext* context, const ::helloworld::FamilyRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetNameRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReaderWriter< ::helloworld::FamilyRequest, ::helloworld::FamilyResponse>* Greeter::Stub::ListNameRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::helloworld::FamilyRequest, ::helloworld::FamilyResponse>::Create(channel_.get(), rpcmethod_ListName_, context);
}

void Greeter::Stub::async::ListName(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::helloworld::FamilyRequest,::helloworld::FamilyResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::helloworld::FamilyRequest,::helloworld::FamilyResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_ListName_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::helloworld::FamilyRequest, ::helloworld::FamilyResponse>* Greeter::Stub::AsyncListNameRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::helloworld::FamilyRequest, ::helloworld::FamilyResponse>::Create(channel_.get(), cq, rpcmethod_ListName_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::helloworld::FamilyRequest, ::helloworld::FamilyResponse>* Greeter::Stub::PrepareAsyncListNameRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::helloworld::FamilyRequest, ::helloworld::FamilyResponse>::Create(channel_.get(), cq, rpcmethod_ListName_, context, false, nullptr);
}

::grpc::ClientWriter< ::helloworld::HelloRequest>* Greeter::Stub::ClientStreamSayHelloRaw(::grpc::ClientContext* context, ::helloworld::HelloReply* response) {
  return ::grpc::internal::ClientWriterFactory< ::helloworld::HelloRequest>::Create(channel_.get(), rpcmethod_ClientStreamSayHello_, context, response);
}

void Greeter::Stub::async::ClientStreamSayHello(::grpc::ClientContext* context, ::helloworld::HelloReply* response, ::grpc::ClientWriteReactor< ::helloworld::HelloRequest>* reactor) {
  ::grpc::internal::ClientCallbackWriterFactory< ::helloworld::HelloRequest>::Create(stub_->channel_.get(), stub_->rpcmethod_ClientStreamSayHello_, context, response, reactor);
}

::grpc::ClientAsyncWriter< ::helloworld::HelloRequest>* Greeter::Stub::AsyncClientStreamSayHelloRaw(::grpc::ClientContext* context, ::helloworld::HelloReply* response, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::helloworld::HelloRequest>::Create(channel_.get(), cq, rpcmethod_ClientStreamSayHello_, context, response, true, tag);
}

::grpc::ClientAsyncWriter< ::helloworld::HelloRequest>* Greeter::Stub::PrepareAsyncClientStreamSayHelloRaw(::grpc::ClientContext* context, ::helloworld::HelloReply* response, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::helloworld::HelloRequest>::Create(channel_.get(), cq, rpcmethod_ClientStreamSayHello_, context, response, false, nullptr);
}

::grpc::ClientReader< ::helloworld::HelloReply>* Greeter::Stub::ServerStreamSayHelloRaw(::grpc::ClientContext* context, const ::helloworld::HelloRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::helloworld::HelloReply>::Create(channel_.get(), rpcmethod_ServerStreamSayHello_, context, request);
}

void Greeter::Stub::async::ServerStreamSayHello(::grpc::ClientContext* context, const ::helloworld::HelloRequest* request, ::grpc::ClientReadReactor< ::helloworld::HelloReply>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::helloworld::HelloReply>::Create(stub_->channel_.get(), stub_->rpcmethod_ServerStreamSayHello_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::helloworld::HelloReply>* Greeter::Stub::AsyncServerStreamSayHelloRaw(::grpc::ClientContext* context, const ::helloworld::HelloRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::helloworld::HelloReply>::Create(channel_.get(), cq, rpcmethod_ServerStreamSayHello_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::helloworld::HelloReply>* Greeter::Stub::PrepareAsyncServerStreamSayHelloRaw(::grpc::ClientContext* context, const ::helloworld::HelloRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::helloworld::HelloReply>::Create(channel_.get(), cq, rpcmethod_ServerStreamSayHello_, context, request, false, nullptr);
}

Greeter::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Greeter_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Greeter::Service, ::helloworld::HelloRequest, ::helloworld::HelloReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Greeter::Service* service,
             ::grpc::ServerContext* ctx,
             const ::helloworld::HelloRequest* req,
             ::helloworld::HelloReply* resp) {
               return service->SayHello(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Greeter_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Greeter::Service, ::helloworld::FamilyRequest, ::helloworld::FamilyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Greeter::Service* service,
             ::grpc::ServerContext* ctx,
             const ::helloworld::FamilyRequest* req,
             ::helloworld::FamilyResponse* resp) {
               return service->GetName(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Greeter_method_names[2],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< Greeter::Service, ::helloworld::FamilyRequest, ::helloworld::FamilyResponse>(
          [](Greeter::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::helloworld::FamilyResponse,
             ::helloworld::FamilyRequest>* stream) {
               return service->ListName(ctx, stream);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Greeter_method_names[3],
      ::grpc::internal::RpcMethod::CLIENT_STREAMING,
      new ::grpc::internal::ClientStreamingHandler< Greeter::Service, ::helloworld::HelloRequest, ::helloworld::HelloReply>(
          [](Greeter::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReader<::helloworld::HelloRequest>* reader,
             ::helloworld::HelloReply* resp) {
               return service->ClientStreamSayHello(ctx, reader, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Greeter_method_names[4],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< Greeter::Service, ::helloworld::HelloRequest, ::helloworld::HelloReply>(
          [](Greeter::Service* service,
             ::grpc::ServerContext* ctx,
             const ::helloworld::HelloRequest* req,
             ::grpc::ServerWriter<::helloworld::HelloReply>* writer) {
               return service->ServerStreamSayHello(ctx, req, writer);
             }, this)));
}

Greeter::Service::~Service() {
}

::grpc::Status Greeter::Service::SayHello(::grpc::ServerContext* context, const ::helloworld::HelloRequest* request, ::helloworld::HelloReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Greeter::Service::GetName(::grpc::ServerContext* context, const ::helloworld::FamilyRequest* request, ::helloworld::FamilyResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Greeter::Service::ListName(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::helloworld::FamilyResponse, ::helloworld::FamilyRequest>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Greeter::Service::ClientStreamSayHello(::grpc::ServerContext* context, ::grpc::ServerReader< ::helloworld::HelloRequest>* reader, ::helloworld::HelloReply* response) {
  (void) context;
  (void) reader;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Greeter::Service::ServerStreamSayHello(::grpc::ServerContext* context, const ::helloworld::HelloRequest* request, ::grpc::ServerWriter< ::helloworld::HelloReply>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* GreeterAgain_method_names[] = {
  "/helloworld.GreeterAgain/SayHello",
  "/helloworld.GreeterAgain/GetName",
  "/helloworld.GreeterAgain/ListName",
  "/helloworld.GreeterAgain/ClientStreamSayHello",
  "/helloworld.GreeterAgain/ServerStreamSayHello",
};

std::unique_ptr< GreeterAgain::Stub> GreeterAgain::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< GreeterAgain::Stub> stub(new GreeterAgain::Stub(channel, options));
  return stub;
}

GreeterAgain::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SayHello_(GreeterAgain_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetName_(GreeterAgain_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListName_(GreeterAgain_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  , rpcmethod_ClientStreamSayHello_(GreeterAgain_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::CLIENT_STREAMING, channel)
  , rpcmethod_ServerStreamSayHello_(GreeterAgain_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::Status GreeterAgain::Stub::SayHello(::grpc::ClientContext* context, const ::helloworld::HelloRequest& request, ::helloworld::HelloReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::helloworld::HelloRequest, ::helloworld::HelloReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SayHello_, context, request, response);
}

void GreeterAgain::Stub::async::SayHello(::grpc::ClientContext* context, const ::helloworld::HelloRequest* request, ::helloworld::HelloReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::helloworld::HelloRequest, ::helloworld::HelloReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SayHello_, context, request, response, std::move(f));
}

void GreeterAgain::Stub::async::SayHello(::grpc::ClientContext* context, const ::helloworld::HelloRequest* request, ::helloworld::HelloReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SayHello_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::helloworld::HelloReply>* GreeterAgain::Stub::PrepareAsyncSayHelloRaw(::grpc::ClientContext* context, const ::helloworld::HelloRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::helloworld::HelloReply, ::helloworld::HelloRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SayHello_, context, request);
}

::grpc::ClientAsyncResponseReader< ::helloworld::HelloReply>* GreeterAgain::Stub::AsyncSayHelloRaw(::grpc::ClientContext* context, const ::helloworld::HelloRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSayHelloRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status GreeterAgain::Stub::GetName(::grpc::ClientContext* context, const ::helloworld::FamilyRequest& request, ::helloworld::FamilyResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::helloworld::FamilyRequest, ::helloworld::FamilyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetName_, context, request, response);
}

void GreeterAgain::Stub::async::GetName(::grpc::ClientContext* context, const ::helloworld::FamilyRequest* request, ::helloworld::FamilyResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::helloworld::FamilyRequest, ::helloworld::FamilyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetName_, context, request, response, std::move(f));
}

void GreeterAgain::Stub::async::GetName(::grpc::ClientContext* context, const ::helloworld::FamilyRequest* request, ::helloworld::FamilyResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetName_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::helloworld::FamilyResponse>* GreeterAgain::Stub::PrepareAsyncGetNameRaw(::grpc::ClientContext* context, const ::helloworld::FamilyRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::helloworld::FamilyResponse, ::helloworld::FamilyRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetName_, context, request);
}

::grpc::ClientAsyncResponseReader< ::helloworld::FamilyResponse>* GreeterAgain::Stub::AsyncGetNameRaw(::grpc::ClientContext* context, const ::helloworld::FamilyRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetNameRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReaderWriter< ::helloworld::FamilyRequest, ::helloworld::FamilyResponse>* GreeterAgain::Stub::ListNameRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::helloworld::FamilyRequest, ::helloworld::FamilyResponse>::Create(channel_.get(), rpcmethod_ListName_, context);
}

void GreeterAgain::Stub::async::ListName(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::helloworld::FamilyRequest,::helloworld::FamilyResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::helloworld::FamilyRequest,::helloworld::FamilyResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_ListName_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::helloworld::FamilyRequest, ::helloworld::FamilyResponse>* GreeterAgain::Stub::AsyncListNameRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::helloworld::FamilyRequest, ::helloworld::FamilyResponse>::Create(channel_.get(), cq, rpcmethod_ListName_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::helloworld::FamilyRequest, ::helloworld::FamilyResponse>* GreeterAgain::Stub::PrepareAsyncListNameRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::helloworld::FamilyRequest, ::helloworld::FamilyResponse>::Create(channel_.get(), cq, rpcmethod_ListName_, context, false, nullptr);
}

::grpc::ClientWriter< ::helloworld::HelloRequest>* GreeterAgain::Stub::ClientStreamSayHelloRaw(::grpc::ClientContext* context, ::helloworld::HelloReply* response) {
  return ::grpc::internal::ClientWriterFactory< ::helloworld::HelloRequest>::Create(channel_.get(), rpcmethod_ClientStreamSayHello_, context, response);
}

void GreeterAgain::Stub::async::ClientStreamSayHello(::grpc::ClientContext* context, ::helloworld::HelloReply* response, ::grpc::ClientWriteReactor< ::helloworld::HelloRequest>* reactor) {
  ::grpc::internal::ClientCallbackWriterFactory< ::helloworld::HelloRequest>::Create(stub_->channel_.get(), stub_->rpcmethod_ClientStreamSayHello_, context, response, reactor);
}

::grpc::ClientAsyncWriter< ::helloworld::HelloRequest>* GreeterAgain::Stub::AsyncClientStreamSayHelloRaw(::grpc::ClientContext* context, ::helloworld::HelloReply* response, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::helloworld::HelloRequest>::Create(channel_.get(), cq, rpcmethod_ClientStreamSayHello_, context, response, true, tag);
}

::grpc::ClientAsyncWriter< ::helloworld::HelloRequest>* GreeterAgain::Stub::PrepareAsyncClientStreamSayHelloRaw(::grpc::ClientContext* context, ::helloworld::HelloReply* response, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::helloworld::HelloRequest>::Create(channel_.get(), cq, rpcmethod_ClientStreamSayHello_, context, response, false, nullptr);
}

::grpc::ClientReader< ::helloworld::HelloReply>* GreeterAgain::Stub::ServerStreamSayHelloRaw(::grpc::ClientContext* context, const ::helloworld::HelloRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::helloworld::HelloReply>::Create(channel_.get(), rpcmethod_ServerStreamSayHello_, context, request);
}

void GreeterAgain::Stub::async::ServerStreamSayHello(::grpc::ClientContext* context, const ::helloworld::HelloRequest* request, ::grpc::ClientReadReactor< ::helloworld::HelloReply>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::helloworld::HelloReply>::Create(stub_->channel_.get(), stub_->rpcmethod_ServerStreamSayHello_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::helloworld::HelloReply>* GreeterAgain::Stub::AsyncServerStreamSayHelloRaw(::grpc::ClientContext* context, const ::helloworld::HelloRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::helloworld::HelloReply>::Create(channel_.get(), cq, rpcmethod_ServerStreamSayHello_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::helloworld::HelloReply>* GreeterAgain::Stub::PrepareAsyncServerStreamSayHelloRaw(::grpc::ClientContext* context, const ::helloworld::HelloRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::helloworld::HelloReply>::Create(channel_.get(), cq, rpcmethod_ServerStreamSayHello_, context, request, false, nullptr);
}

GreeterAgain::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      GreeterAgain_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< GreeterAgain::Service, ::helloworld::HelloRequest, ::helloworld::HelloReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](GreeterAgain::Service* service,
             ::grpc::ServerContext* ctx,
             const ::helloworld::HelloRequest* req,
             ::helloworld::HelloReply* resp) {
               return service->SayHello(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      GreeterAgain_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< GreeterAgain::Service, ::helloworld::FamilyRequest, ::helloworld::FamilyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](GreeterAgain::Service* service,
             ::grpc::ServerContext* ctx,
             const ::helloworld::FamilyRequest* req,
             ::helloworld::FamilyResponse* resp) {
               return service->GetName(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      GreeterAgain_method_names[2],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< GreeterAgain::Service, ::helloworld::FamilyRequest, ::helloworld::FamilyResponse>(
          [](GreeterAgain::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::helloworld::FamilyResponse,
             ::helloworld::FamilyRequest>* stream) {
               return service->ListName(ctx, stream);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      GreeterAgain_method_names[3],
      ::grpc::internal::RpcMethod::CLIENT_STREAMING,
      new ::grpc::internal::ClientStreamingHandler< GreeterAgain::Service, ::helloworld::HelloRequest, ::helloworld::HelloReply>(
          [](GreeterAgain::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReader<::helloworld::HelloRequest>* reader,
             ::helloworld::HelloReply* resp) {
               return service->ClientStreamSayHello(ctx, reader, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      GreeterAgain_method_names[4],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< GreeterAgain::Service, ::helloworld::HelloRequest, ::helloworld::HelloReply>(
          [](GreeterAgain::Service* service,
             ::grpc::ServerContext* ctx,
             const ::helloworld::HelloRequest* req,
             ::grpc::ServerWriter<::helloworld::HelloReply>* writer) {
               return service->ServerStreamSayHello(ctx, req, writer);
             }, this)));
}

GreeterAgain::Service::~Service() {
}

::grpc::Status GreeterAgain::Service::SayHello(::grpc::ServerContext* context, const ::helloworld::HelloRequest* request, ::helloworld::HelloReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status GreeterAgain::Service::GetName(::grpc::ServerContext* context, const ::helloworld::FamilyRequest* request, ::helloworld::FamilyResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status GreeterAgain::Service::ListName(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::helloworld::FamilyResponse, ::helloworld::FamilyRequest>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status GreeterAgain::Service::ClientStreamSayHello(::grpc::ServerContext* context, ::grpc::ServerReader< ::helloworld::HelloRequest>* reader, ::helloworld::HelloReply* response) {
  (void) context;
  (void) reader;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status GreeterAgain::Service::ServerStreamSayHello(::grpc::ServerContext* context, const ::helloworld::HelloRequest* request, ::grpc::ServerWriter< ::helloworld::HelloReply>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* NameServer_method_names[] = {
  "/helloworld.NameServer/ListName",
};

std::unique_ptr< NameServer::Stub> NameServer::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< NameServer::Stub> stub(new NameServer::Stub(channel, options));
  return stub;
}

NameServer::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_ListName_(NameServer_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::ClientReaderWriter< ::helloworld::FamilyRequest, ::helloworld::FamilyResponse>* NameServer::Stub::ListNameRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::helloworld::FamilyRequest, ::helloworld::FamilyResponse>::Create(channel_.get(), rpcmethod_ListName_, context);
}

void NameServer::Stub::async::ListName(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::helloworld::FamilyRequest,::helloworld::FamilyResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::helloworld::FamilyRequest,::helloworld::FamilyResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_ListName_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::helloworld::FamilyRequest, ::helloworld::FamilyResponse>* NameServer::Stub::AsyncListNameRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::helloworld::FamilyRequest, ::helloworld::FamilyResponse>::Create(channel_.get(), cq, rpcmethod_ListName_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::helloworld::FamilyRequest, ::helloworld::FamilyResponse>* NameServer::Stub::PrepareAsyncListNameRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::helloworld::FamilyRequest, ::helloworld::FamilyResponse>::Create(channel_.get(), cq, rpcmethod_ListName_, context, false, nullptr);
}

NameServer::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      NameServer_method_names[0],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< NameServer::Service, ::helloworld::FamilyRequest, ::helloworld::FamilyResponse>(
          [](NameServer::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::helloworld::FamilyResponse,
             ::helloworld::FamilyRequest>* stream) {
               return service->ListName(ctx, stream);
             }, this)));
}

NameServer::Service::~Service() {
}

::grpc::Status NameServer::Service::ListName(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::helloworld::FamilyResponse, ::helloworld::FamilyRequest>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace helloworld

